<a href="https://colab.research.google.com/github/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/blob/main/IM_Etude_de_march%C3%A9_poulets_francais_Preparation_donn%C3%A9es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as ticker

from scipy import stats
import seaborn as sns

# **Importation des données**

In [2]:
# URL vers les fichiers CSV hébergés sur GitHub
url_corruption_control = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Controle_Corruption_2021.csv'
url_cost_animal_source_food_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Cost_of_animal_source_foods_2021.csv'
url_epi_2018= 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/EPI_2018.csv'
url_epi_2020 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/EPI_2020.csv'
url_epi_2022 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/EPI_2022.csv'
url_governance_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Governance_2021.csv'
url_inflation_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/inflation_2021.csv'
url_lpi_2007_2022 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/LPI_2007_2022.csv'
url_pib_par_habitant_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/PIB_par_habitant_2021.csv'
url_stabilite_politique_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Stabilite%CC%81_politique_2021.csv'
url_quantité_production_poulet_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Quantite%CC%81_production_poulet_2021.csv'
url_taux_change_2021= 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Taux_change_2021.csv'
url_population_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Population_2021.csv'
url_dispo_proteine_2021 = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Disponibilite_Proteine_Viande_et_produits_carne%CC%81s_2021.csv'
url_code_pays = 'https://raw.githubusercontent.com/Ichraf-MOUELHI/Etude_de_marche_poulet_Francais_2018-2022/refs/heads/main/Code_pays.csv'


# Chargement des fichiers directement depuis GitHub
corruption_control = pd.read_csv(url_corruption_control)
cost_animal_source_food_2021 = pd.read_csv(url_cost_animal_source_food_2021)
epi_2018 = pd.read_csv(url_epi_2018)
epi_2020 = pd.read_csv(url_epi_2020)
epi_2022 = pd.read_csv(url_epi_2022)
governance_2021 = pd.read_csv(url_governance_2021)
inflation_2021 = pd.read_csv(url_inflation_2021)
lpi_2007_2022 = pd.read_csv(url_lpi_2007_2022)
pib_par_habitant_2021 = pd.read_csv(url_pib_par_habitant_2021)
stabilite_politique_2021 = pd.read_csv(url_stabilite_politique_2021)
quantité_production_poulet_2021 = pd.read_csv(url_quantité_production_poulet_2021)
taux_change_2021 = pd.read_csv(url_taux_change_2021)
population_2021 = pd.read_csv(url_population_2021)
dispo_proteine_2021 = pd.read_csv(url_dispo_proteine_2021)
code_pays = pd.read_csv(url_code_pays)

# **Définition des variables**

* **EPI**

L'Environmental Performance Index (EPI), ou Indice de performance environnementale, est un outil utilisé pour évaluer la performance environnementale des pays. Créé par des institutions telles que Yale et Columbia, il se base sur deux axes principaux : la santé environnementale, mesurant l'impact de l'environnement sur la santé humaine, et la vitalité des écosystèmes, qui évalue la protection des écosystèmes et la gestion des ressources naturelles.

L'EPI sert à comparer les performances des pays sur divers aspects environnementaux (pollution de l'air, gestion des déchets, changement climatique), à suivre les progrès et à fournir des recommandations aux décideurs politiques. Les indicateurs clés incluent la qualité de l'air, la gestion de l'eau, la biodiversité, et les émissions de gaz à effet de serre.

Chaque pays reçoit une note sur 100 pour chaque indicateur, avec une pondération pour refléter l'importance des catégories. L'EPI est donc essentiel pour évaluer l'efficacité des politiques environnementales, identifier les domaines à améliorer et suivre les progrès vers les Objectifs de développement durable (ODD).

* **LPI**

Le Logistics Performance Index (LPI) est un indicateur élaboré par la Banque mondiale pour évaluer la performance logistique des pays. Il mesure l'efficacité des flux de marchandises au sein des frontières et au-delà, en s'appuyant sur plusieurs dimensions.

Le score global, compris entre 1 (faible performance) et 5 (excellente performance), reflète différents aspects logistiques tels que :

Efficacité des procédures douanières
Qualité des infrastructures logistiques
Facilité d'expédition internationale
Compétence des services logistiques
Suivi et traçabilité des envois
Fréquence des livraisons à temps
L'objectif du LPI est de permettre la comparaison internationale de la performance logistique, fournissant des informations utiles aux décideurs pour améliorer le commerce et la compétitivité. Les données sont collectées via des enquêtes auprès de professionnels et sont publiées tous les deux ans.

* **Coahd**

L'indicateur Coût et abordabilité d’une alimentation saine (CoAHD) évalue si une population, notamment les plus vulnérables, peut se permettre une alimentation équilibrée respectant les recommandations nutritionnelles. Il se base sur deux aspects principaux :

Coût d’une alimentation saine : Il représente le montant nécessaire pour acheter des aliments nutritifs (fruits, légumes, protéines, etc.) et est calculé sur une base quotidienne ou mensuelle.
Abordabilité : Il compare ce coût au revenu disponible des populations pour déterminer si elles peuvent accéder à une alimentation saine sans compromettre d'autres besoins essentiels (logement, santé, etc.).
Des facteurs comme le prix des denrées alimentaires, le revenu moyen, l'accès aux marchés et les politiques publiques influencent le CoAHD. Cet indicateur est essentiel pour évaluer la sécurité alimentaire, les inégalités économiques, et pour orienter les politiques publiques vers une alimentation plus accessible et abordable.
-> Choix sur l'indicateur cost_animal_source_food (PPP)

* **Governance Effectiveness**

Efficacité du gouvernement : reflète la perception de la qualité des services publics, de la qualité de la fonction publique et de son degré d'indépendance par rapport aux pressions politiques, de la qualité de la formulation et de la mise en œuvre des politiques, et de la crédibilité de l'engagement du gouvernement à l'égard de ces politiques.

* **Inflation**

L'indicateur de l'inflation, mesuré par le pourcentage annuel de variation des prix à la consommation, montre l'évolution des prix des biens et services dans une économie sur une année. Il est basé sur l'Indice des Prix à la Consommation (IPC), qui suit les prix d'un panier fixe de produits représentatifs (alimentation, logement, transport). Un taux positif indique une hausse des prix (inflation), tandis qu'un taux négatif montre une baisse (déflation).

L'inflation, comme dans l'exemple d'un taux de 53%, implique une forte augmentation des prix, une baisse du pouvoir d'achat, et peut signaler de graves déséquilibres économiques. Ce phénomène peut affecter la confiance dans la monnaie et engendrer des crises économiques, telles que l'hyperinflation. Les acteurs économiques doivent alors s'adapter à ces conditions difficiles.

* **Corruption Control**

Contrôle de la corruption : Reflète la perception de la mesure dans laquelle le pouvoir public est exercé à des fins privées, y compris les petites et grandes formes de corruption, ainsi que la « capture » de l'État par les élites et les intérêts privés.

* **PIB par habitant (unités de devises locales constantes)** (sur taux de change en euros pour pouvoir comparer)

Le PIB par habitant est un indicateur économique qui mesure la valeur des biens et services produits dans un pays sur une période donnée, divisée par le nombre d'habitants. Il permet d'évaluer la richesse et la prospérité économique par personne. Un PIB par habitant élevé et un fort pouvoir d'achat font d'un pays un marché attractif.


* **Stabilité Politique**


L'indicateur "Stabilité politique et absence de violence/terrorisme", développé par la Banque mondiale, évalue la probabilité qu'un gouvernement soit déstabilisé ou renversé par des moyens violents, y compris le terrorisme. Il se concentre sur deux aspects :

Stabilité politique : mesure la perception de la durabilité du gouvernement, c'est-à-dire sa capacité à rester en place sans faire face à des troubles majeurs comme des coups d'État ou des révolutions.
Violence et terrorisme : évalue la prévalence de la violence politique, y compris les actes de terrorisme et les conflits internes.
Cet indice est noté de -2,5 à +2,5, où +2,5 indique une forte stabilité et une quasi-absence de violence, et -2,5 reflète une grande instabilité accompagnée d'une forte prévalence de violence et de terrorisme.

* **Quantité de production du poulet**

L'indicateur "Quantité production poulet (tonnes)" représente le volume total de viande de poulet produite sur une période donnée, exprimée en tonnes. Cet indicateur mesure la quantité de poulet transformée et prête pour la consommation, incluant l'élevage, l'abattage et la transformation des volailles. Il est utilisé pour évaluer la capacité de production d'un pays, d'une région ou d'une entreprise dans le secteur avicole, et sert à analyser des aspects tels que l'approvisionnement alimentaire, la compétitivité de l'industrie, et les dynamiques du marché des produits avicoles.

* **Taux de change**

Le taux de change officiel représente le prix d'une monnaie nationale par rapport au dollar américain. Cet indicateur exprime combien d'unités de la monnaie locale sont nécessaires pour obtenir un dollar, calculé en moyenne sur une période donnée (mois ou année). Il sert à suivre la valeur relative d'une monnaie, analyser sa stabilité ou ses fluctuations, et aider les décideurs économiques à évaluer l'impact des taux de change sur le commerce, l'investissement et d'autres aspects économiques. Les variations monétaires influencent aussi le coût et la compétitivité des exportations.


* **Population**

La population totale est basée sur la définition de facto de la population, qui compte tous les résidents, quel que soit leur statut juridique ou leur citoyenneté. Les valeurs indiquées sont des estimations de mi-année.

* **Disponibilité en Proteine**

L'indicateur "Disponibilité alimentaire en protéines" mesure la quantité de protéines alimentaires disponible pour la consommation par habitant, généralement exprimée en grammes par personne et par jour. Il évalue l'accès aux sources de protéines, telles que la viande, le poisson, les produits laitiers, et les légumineuses.

Les facteurs influençant cet indicateur comprennent la production locale, les importations, les politiques agricoles et les conditions économiques. Il est essentiel pour évaluer la sécurité alimentaire et la nutrition des populations, identifier les besoins en améliorations nutritionnelles, et comparer la situation nutritionnelle entre différentes régions.

# Nettoyage des données

* EPI

In [3]:
# Jointure  entre epi_2018 et 2020
epi_merged = pd.merge(epi_2018, epi_2020, on=['code', 'country', 'iso'], how='outer', suffixes=('_2018', '_2020'))
epi_total = pd.merge(epi_merged, epi_2022, on=['code', 'country', 'iso'], how='outer', suffixes=('', '_2022'))

In [4]:
epi_total

     code  iso              country EPI.2018 EPI.2020 EPI.2022
0       4  AFG          Afghanistan    37,74     25,5     43,6
1       8  ALB              Albania    65,46       49     47,1
2      12  DZA              Algeria    57,18     44,8     29,6
3      24  AGO               Angola    37,44     29,7     30,5
4      28  ATG  Antigua and Barbuda    59,18     48,5     52,4
..    ...  ...                  ...      ...      ...      ...
180   858  URY              Uruguay    64,65     49,1     37,4
181   860  UZB           Uzbekistan    45,88     44,3     38,2
182   862  VEN            Venezuela    63,89     50,3     46,4
183   882  WSM                Samoa     54,5     37,3     36,4
184   894  ZMB               Zambia    50,97     34,7     38,4

[185 rows x 6 columns]

In [5]:
epi_total.nunique()

code        181
iso         181
country     185
EPI.2018    178
EPI.2020    153
EPI.2022    148
dtype: int64

In [6]:
epi_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      185 non-null    int64
 1   iso       185 non-null    object
 2   country   185 non-null    object
 3   EPI.2018  180 non-null    object
 4   EPI.2020  180 non-null    object
 5   EPI.2022  180 non-null    object
dtypes: int64(1), object(5)
memory usage: 8.8+ KB

In [7]:
epi_total.isna().sum()

code        0
iso         0
country     0
EPI.2018    5
EPI.2020    5
EPI.2022    5
dtype: int64

In [8]:
for column in epi_total.columns:
    num_duplicates = epi_total[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'code': 4 duplicates
Column 'iso': 4 duplicates
Column 'country': 0 duplicates
Column 'EPI.2018': 6 duplicates
Column 'EPI.2020': 31 duplicates
Column 'EPI.2022': 36 duplicates

In [9]:
# Visualiser les lignes présentant des doublons
duplicate_rows = epi_total[epi_total.duplicated(subset=['code', 'iso'], keep=False)]
print(duplicate_rows)

     code  iso                   country EPI.2018 EPI.2020 EPI.2022
82    384  CIV             Cote d'Ivoire      NaN     25,8     32,8
83    384  CIV          CÃƒÂ´te d'Ivoire    45,25      NaN      NaN
142   678  STP     Sao Tome and Principe      NaN     37,6     52,9
143   678  STP  SÃƒÂ£o TomÃƒÂ© and PrÃƒÂ    54,01      NaN      NaN
158   748  SWZ                  Eswatini      NaN     33,8     44,9
159   748  SWZ                 Swaziland    40,32      NaN      NaN
173   807  MKD                 Macedonia    61,06      NaN      NaN
174   807  MKD           North Macedonia      NaN     55,4     54,3

In [10]:
# Replace incorrect country names with the correct ones
epi_total['country'] = epi_total['country'].replace({"CÃƒÂ´te d'Ivoire": "Cote d'Ivoire",
                                                      "SÃƒÂ£o TomÃƒÂ© and PrÃƒÂ": "Sao Tome and Principe", "North Macedonia" : "Macedonia", "Swaziland" : "Eswatini"})

# Group by 'code' and 'iso' and take the first non-null value for EPI columns
epi_total = epi_total.groupby(['code', 'iso', 'country'])[['EPI.2018', 'EPI.2020', 'EPI.2022']].first().reset_index()

In [11]:
duplicate_rows = epi_total[epi_total.duplicated(subset=['code', 'iso'], keep=False)]
print(duplicate_rows)

Empty DataFrame
Columns: [code, iso, country, EPI.2018, EPI.2020, EPI.2022]
Index: []

In [12]:
# Vérifier les doublons de chaque colonnes
for column in epi_total.columns:
    num_duplicates = epi_total[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'code': 0 duplicates
Column 'iso': 0 duplicates
Column 'country': 0 duplicates
Column 'EPI.2018': 2 duplicates
Column 'EPI.2020': 27 duplicates
Column 'EPI.2022': 32 duplicates

In [13]:
# Remplacement des virgules par des points
epi_total['EPI.2018'] = epi_total['EPI.2018'].str.replace(',', '.')
epi_total['EPI.2020'] = epi_total['EPI.2020'].str.replace(',', '.')
epi_total['EPI.2022'] = epi_total['EPI.2022'].str.replace(',', '.')

# Changer le type dtype des colonnes
epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']] = epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']].astype(float)

In [14]:
epi_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   code      181 non-null    int64
 1   iso       181 non-null    object
 2   country   181 non-null    object
 3   EPI.2018  180 non-null    float64
 4   EPI.2020  180 non-null    float64
 5   EPI.2022  180 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 8.6+ KB

In [15]:
# Calculer la moyenne et la médiane des colonnes EPI
epi_total['moyenne_epi'] = epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']].mean(axis=1)
epi_total['mediane_epi'] = epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']].median(axis=1)

In [16]:
epi_total['moyenne_epi'] = epi_total['moyenne_epi'].round(2)

In [17]:
# Remplacer Nan par 0
epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']] = epi_total[['EPI.2018', 'EPI.2020', 'EPI.2022']].fillna(0)
epi_total

,code,iso,country,EPI.2018,EPI.2020,EPI.2022,moyenne_epi,mediane_epi
0,4,AFG,Afghanistan,37.74,25.5,43.6,35.61,37.74
1,8,ALB,Albania,65.46,49.0,47.1,53.85,49.00
2,12,DZA,Algeria,57.18,44.8,29.6,43.86,44.80
3,24,AGO,Angola,37.44,29.7,30.5,32.55,30.50
4,28,ATG,Antigua and Barbuda,59.18,48.5,52.4,53.36,52.40
...,...,...,...,...,...,...,...,...
176,858,URY,Uruguay,64.65,49.1,37.4,50.38,49.10
177,860,UZB,Uzbekistan,45.88,44.3,38.2,42.79,44.30
178,862,VEN,Venezuela,63.89,50.3,46.4,53.53,50.30
179,882,WSM,Samoa,54.50,37.3,36.4,42.73,37.30
180,894,ZMB,Zambia,50.97,34.7,38.4,41.36,38.40

In [18]:
for column in epi_total.columns:
    num_duplicates = epi_total['country'].duplicated().sum()
    print(f"Column '{'country'}': {num_duplicates} duplicates")

Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates
Column 'country': 0 duplicates

In [19]:
epi_total.describe()

,code,EPI.2018,EPI.2020,EPI.2022,moyenne_epi,mediane_epi
count,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000
mean,420.475138,56.097238,46.187293,42.865193,48.628177,47.915028
std,253.355735,13.489952,15.789645,12.675043,12.818794,14.378808
min,4.000000,0.000000,0.000000,0.000000,25.690000,24.900000
25%,203.000000,45.880000,33.900000,33.900000,38.550000,36.900000
50%,417.000000,56.180000,44.000000,41.900000,47.080000,45.100000
75%,634.000000,64.710000,54.800000,50.600000,55.490000,54.990000
max,894.000000,87.420000,82.500000,77.900000,80.670000,81.600000

# Nettoyage


* **Corruption**

In [20]:
corruption_control.head()

  Country/Territory Code Estimate
0             Aruba  ABW     0,80
1           Andorra  ADO     1,28
2       Afghanistan  AFG    -1,15
3            Angola  AGO    -0,65
4          Anguilla  AIA     0,64

In [21]:
# Changer les titres des colonnes
corruption_control.rename(columns={'Country/Territory': 'Country', 'Estimate':'Corruption_Value'}, inplace=True)

In [22]:
corruption_control.head()

       Country Code Corruption_Value
0        Aruba  ABW             0,80
1      Andorra  ADO             1,28
2  Afghanistan  AFG            -1,15
3       Angola  AGO            -0,65
4     Anguilla  AIA             0,64

In [23]:
corruption_control.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           214 non-null    object
 1   Code              214 non-null    object
 2   Corruption_Value  211 non-null    object
dtypes: object(3)
memory usage: 5.1+ KB

In [24]:
# Remplacement des virgules par des points
corruption_control['Corruption_Value'] = corruption_control['Corruption_Value'].str.replace(',', '.')

# Changer le type dtype des colonnes
corruption_control[['Corruption_Value']] = corruption_control[['Corruption_Value']].astype(float)

In [25]:
corruption_control.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           214 non-null    object
 1   Code              214 non-null    object
 2   Corruption_Value  211 non-null    float64
dtypes: float64(1), object(2)
memory usage: 5.1+ KB

In [26]:
corruption_control

              Country Code  Corruption_Value
0               Aruba  ABW              0.80
1             Andorra  ADO              1.28
2         Afghanistan  AFG             -1.15
3              Angola  AGO             -0.65
4            Anguilla  AIA              0.64
..                ...  ...               ...
209            Serbia  SRB             -0.46
210      South Africa  ZAF             -0.03
211  Congo, Dem. Rep.  ZAR             -1.57
212            Zambia  ZMB             -0.76
213          Zimbabwe  ZWE             -1.25

[214 rows x 3 columns]

In [27]:
corruption_control.isna().sum()

Country             0
Code                0
Corruption_Value    3
dtype: int64

In [28]:
corruption_control.nunique()

Country             214
Code                214
Corruption_Value    154
dtype: int64

In [29]:
# Vérifier les doublons
for column in corruption_control.columns:
    num_duplicates = corruption_control[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country': 0 duplicates
Column 'Code': 0 duplicates
Column 'Corruption_Value': 59 duplicates

In [30]:
corruption_control.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           214 non-null    object
 1   Code              214 non-null    object
 2   Corruption_Value  211 non-null    float64
dtypes: float64(1), object(2)
memory usage: 5.1+ KB

In [31]:
corruption_control.isna().sum()

Country             0
Code                0
Corruption_Value    3
dtype: int64

In [32]:
corruption_control

              Country Code  Corruption_Value
0               Aruba  ABW              0.80
1             Andorra  ADO              1.28
2         Afghanistan  AFG             -1.15
3              Angola  AGO             -0.65
4            Anguilla  AIA              0.64
..                ...  ...               ...
209            Serbia  SRB             -0.46
210      South Africa  ZAF             -0.03
211  Congo, Dem. Rep.  ZAR             -1.57
212            Zambia  ZMB             -0.76
213          Zimbabwe  ZWE             -1.25

[214 rows x 3 columns]

# Nettoyage
* **cost_animal_source_food_2021**

In [33]:
cost_animal_source_food_2021

,Code,Country,Cost of animal source foods valeur \n(PPP dollar per person per day)
0,4,Afghanistan,NaN
1,710,Afrique du Sud,"1,1"
2,8,Albanie,"1,2"
3,12,Algérie,"1,3"
4,276,Allemagne,"0,7"
...,...,...,...
204,862,Venezuela (République bolivarienne du),NaN
205,704,Viet Nam,"1,2"
206,887,Yémen,NaN
207,894,Zambie,1
208,716,Zimbabwe,NaN

In [34]:
cost_animal_source_food_2021.isna().sum()

Code                                                                     0
Country                                                                  0
Cost of animal source foods valeur \n(PPP dollar per person per day)    43
dtype: int64

In [35]:
cost_animal_source_food_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 3 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Code                                                                 209 non-null    int64
 1   Country                                                              209 non-null    object
 2   Cost of animal source foods valeur
(PPP dollar per person per day)  166 non-null    object
dtypes: int64(1), object(2)
memory usage: 5.0+ KB

In [36]:
# Remplacement des virgules par des points
cost_animal_source_food_2021['Cost of animal source foods valeur \n(PPP dollar per person per day)'] = cost_animal_source_food_2021['Cost of animal source foods valeur \n(PPP dollar per person per day)'].str.replace(',', '.')


# Changer le type dtype des colonnes
cost_animal_source_food_2021[['Cost of animal source foods valeur \n(PPP dollar per person per day)']] = cost_animal_source_food_2021[['Cost of animal source foods valeur \n(PPP dollar per person per day)']].astype(float)
cost_animal_source_food_2021[['Code']] = cost_animal_source_food_2021[['Code']].astype(object)

In [37]:
cost_animal_source_food_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 3 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Code                                                                 209 non-null    object
 1   Country                                                              209 non-null    object
 2   Cost of animal source foods valeur
(PPP dollar per person per day)  166 non-null    float64
dtypes: float64(1), object(2)
memory usage: 5.0+ KB

In [38]:
cost_animal_source_food_2021.nunique()

Code                                                                    209
Country                                                                 209
Cost of animal source foods valeur \n(PPP dollar per person per day)     15
dtype: int64

In [39]:
# Vérifier les doublons
for column in cost_animal_source_food_2021.columns:
    num_duplicates = cost_animal_source_food_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Code': 0 duplicates
Column 'Country': 0 duplicates
Column 'Cost of animal source foods valeur
(PPP dollar per person per day)': 193 duplicates

In [40]:
cost_animal_source_food_2021

,Code,Country,Cost of animal source foods valeur \n(PPP dollar per person per day)
0,4,Afghanistan,NaN
1,710,Afrique du Sud,1.1
2,8,Albanie,1.2
3,12,Algérie,1.3
4,276,Allemagne,0.7
...,...,...,...
204,862,Venezuela (République bolivarienne du),NaN
205,704,Viet Nam,1.2
206,887,Yémen,NaN
207,894,Zambie,1.0
208,716,Zimbabwe,NaN

# Nettoyage
* **governance_2021**

In [41]:
governance_2021

              Country Code Governance performance _-2.5(weak)_2.5(strong)
0               Aruba  ABW                                           1,08
1             Andorra  ADO                                           1,75
2         Afghanistan  AFG                                          -1,67
3              Angola  AGO                                          -1,13
4            Anguilla  AIA                                           0,92
..                ...  ...                                            ...
209            Serbia  SRB                                           0,01
210      South Africa  ZAF                                          -0,07
211  Congo, Dem. Rep.  ZAR                                          -1,76
212            Zambia  ZMB                                          -0,84
213          Zimbabwe  ZWE                                           -1,3

[214 rows x 3 columns]

In [42]:
governance_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 3 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Country                                         214 non-null    object
 1   Code                                            214 non-null    object
 2   Governance performance _-2.5(weak)_2.5(strong)  211 non-null    object
dtypes: object(3)
memory usage: 5.1+ KB

In [43]:
governance_2021 = governance_2021.rename(columns={'Governance performance _-2.5(weak)_2.5(strong)': 'Governance_Performance'})

In [44]:
governance_2021

              Country Code Governance_Performance
0               Aruba  ABW                   1,08
1             Andorra  ADO                   1,75
2         Afghanistan  AFG                  -1,67
3              Angola  AGO                  -1,13
4            Anguilla  AIA                   0,92
..                ...  ...                    ...
209            Serbia  SRB                   0,01
210      South Africa  ZAF                  -0,07
211  Congo, Dem. Rep.  ZAR                  -1,76
212            Zambia  ZMB                  -0,84
213          Zimbabwe  ZWE                   -1,3

[214 rows x 3 columns]

In [45]:
# Remplacement des virgules par des points
governance_2021['Governance_Performance'] = governance_2021['Governance_Performance'].str.replace(',', '.')

# Changer le type dtype des colonnes
governance_2021['Governance_Performance'] = governance_2021['Governance_Performance'].astype(float)

In [46]:
governance_2021

              Country Code  Governance_Performance
0               Aruba  ABW                    1.08
1             Andorra  ADO                    1.75
2         Afghanistan  AFG                   -1.67
3              Angola  AGO                   -1.13
4            Anguilla  AIA                    0.92
..                ...  ...                     ...
209            Serbia  SRB                    0.01
210      South Africa  ZAF                   -0.07
211  Congo, Dem. Rep.  ZAR                   -1.76
212            Zambia  ZMB                   -0.84
213          Zimbabwe  ZWE                   -1.30

[214 rows x 3 columns]

In [47]:
governance_2021.isna().sum()

Country                   0
Code                      0
Governance_Performance    3
dtype: int64

In [48]:
governance_2021.isna().sum()

Country                   0
Code                      0
Governance_Performance    3
dtype: int64

In [49]:
# Vérifier les doublons
for column in governance_2021.columns:
    num_duplicates = governance_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country': 0 duplicates
Column 'Code': 0 duplicates
Column 'Governance_Performance': 59 duplicates

In [50]:
governance_2021.nunique()

Country                   214
Code                      214
Governance_Performance    154
dtype: int64

In [51]:
governance_2021.describe()

       Governance_Performance
count              211.000000
mean                 0.000000
std                  0.999872
min                 -2.400000
25%                 -0.750000
50%                 -0.070000
75%                  0.775000
max                  2.250000

# **NETTOYAGE**

# * **Inflation**

In [52]:
inflation_2021.head()

  Country Name Country Code Inflation, prix à la consommation (% annuel)
0        Aruba          ABW                                          NaN
1          NaN          AFE                                  7,240977656
2  Afghanistan          AFG                                          NaN
3          NaN          AFW                                  3,653532872
4       Angola          AGO                                  25,75429488

In [53]:
#Rennomer la colonne
inflation_2021 = inflation_2021.rename(columns={'Inflation, prix à la consommation (% annuel)': 'Inflation_prix_à_la consommation_%_annuel'})
inflation_2021

       Country Name Country Code Inflation_prix_à_la consommation_%_annuel
0             Aruba          ABW                                       NaN
1               NaN          AFE                               7,240977656
2       Afghanistan          AFG                                       NaN
3               NaN          AFW                               3,653532872
4            Angola          AGO                               25,75429488
..              ...          ...                                       ...
261          Kosovo          XKX                               3,353691392
262  Yémen, Rép. du          YEM                                       NaN
263  Afrique du Sud          ZAF                               4,611672178
264          Zambie          ZMB                               22,02076762
265        Zimbabwe          ZWE                               98,54610509

[266 rows x 3 columns]

In [54]:
# Vérifier les doublons
for column in inflation_2021.columns:
    num_duplicates = inflation_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country Name': 1 duplicates
Column 'Country Code': 0 duplicates
Column 'Inflation_prix_à_la consommation_%_annuel': 72 duplicates

In [55]:
# Visualiser les lignes présentant des doublons
duplicate_rows = inflation_2021[inflation_2021.duplicated(subset=['Country Name'], keep=False)]
print(duplicate_rows)

  Country Name Country Code Inflation_prix_à_la consommation_%_annuel
1          NaN          AFE                               7,240977656
3          NaN          AFW                               3,653532872

In [56]:
# Remplacement des virgules par des points
inflation_2021['Inflation_prix_à_la consommation_%_annuel'] = inflation_2021['Inflation_prix_à_la consommation_%_annuel'].str.replace(',', '.')

# Changer le type dtype des colonnes
inflation_2021[['Inflation_prix_à_la consommation_%_annuel']] = inflation_2021[['Inflation_prix_à_la consommation_%_annuel']].astype(float)
inflation_2021

       Country Name Country Code  Inflation_prix_à_la consommation_%_annuel
0             Aruba          ABW                                        NaN
1               NaN          AFE                                   7.240978
2       Afghanistan          AFG                                        NaN
3               NaN          AFW                                   3.653533
4            Angola          AGO                                  25.754295
..              ...          ...                                        ...
261          Kosovo          XKX                                   3.353691
262  Yémen, Rép. du          YEM                                        NaN
263  Afrique du Sud          ZAF                                   4.611672
264          Zambie          ZMB                                  22.020768
265        Zimbabwe          ZWE                                  98.546105

[266 rows x 3 columns]

In [57]:
inflation_2021

       Country Name Country Code  Inflation_prix_à_la consommation_%_annuel
0             Aruba          ABW                                        NaN
1               NaN          AFE                                   7.240978
2       Afghanistan          AFG                                        NaN
3               NaN          AFW                                   3.653533
4            Angola          AGO                                  25.754295
..              ...          ...                                        ...
261          Kosovo          XKX                                   3.353691
262  Yémen, Rép. du          YEM                                        NaN
263  Afrique du Sud          ZAF                                   4.611672
264          Zambie          ZMB                                  22.020768
265        Zimbabwe          ZWE                                  98.546105

[266 rows x 3 columns]

In [58]:
inflation_2021.round(2)

       Country Name Country Code  Inflation_prix_à_la consommation_%_annuel
0             Aruba          ABW                                        NaN
1               NaN          AFE                                       7.24
2       Afghanistan          AFG                                        NaN
3               NaN          AFW                                       3.65
4            Angola          AGO                                      25.75
..              ...          ...                                        ...
261          Kosovo          XKX                                       3.35
262  Yémen, Rép. du          YEM                                        NaN
263  Afrique du Sud          ZAF                                       4.61
264          Zambie          ZMB                                      22.02
265        Zimbabwe          ZWE                                      98.55

[266 rows x 3 columns]

In [59]:
inflation_2021.describe()

       Inflation_prix_à_la consommation_%_annuel
count                                 219.000000
mean                                    7.521259
std                                    27.329305
min                                    -0.772844
25%                                     2.304663
50%                                     3.653533
75%                                     5.214049
max                                   359.093041

# **NETTOYAGE**

* **Logistic Performance index (lpi) Moyenne sur les années (2007-2022)**

In [60]:
lpi_2007_2022

,Country Name,Country Code,Indice de performance logistique : performance globale (1=faible et 5=élevée),2007,2010,2012,2014,2016,2018,2022,AVG
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#NUM!
1,NaN,AFE,NaN,"2,368095238","2,265","2,409473684","2,432728273","2,528828143","2,475","2,636363636","2,432728273"
2,Afghanistan,AFG,NaN,"1,25","2,09","2,16","2,119709","2,145073","1,92",2,"2,09"
3,NaN,AFW,NaN,"2,282777778","2,301666667","2,435555556","2,38331555","2,302737895","2,316666667","2,52","2,316666667"
4,Angola,AGO,NaN,"2,5","2,02",2,"2,311173","2,31063",2,"2,3","2,3"
...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#NUM!
262,"Yémen, Rép. du",YEM,NaN,"2,22","2,35","2,79","2,207403",NaN,"2,26","2,6","2,305"
263,Afrique du Sud,ZAF,NaN,"3,54","3,59","3,56","3,617883","3,747822","3,19","3,8","3,59"
264,Zambie,ZMB,NaN,"2,44","2,01",NaN,"2,467993","2,415493","2,48",NaN,"2,44"
265,Zimbabwe,ZWE,NaN,"2,21",NaN,"2,27","2,498457","2,12967","2,16","2,3","2,24"

In [61]:
# Remplacement des virgules par des points
lpi_2007_2022['2007'] = lpi_2007_2022['2007'].str.replace(',', '.')
lpi_2007_2022['2010'] = lpi_2007_2022['2010'].str.replace(',', '.')
lpi_2007_2022['2012'] = lpi_2007_2022['2012'].str.replace(',', '.')
lpi_2007_2022['2014'] = lpi_2007_2022['2014'].str.replace(',', '.')
lpi_2007_2022['2016'] = lpi_2007_2022['2016'].str.replace(',', '.')
lpi_2007_2022['2018'] = lpi_2007_2022['2018'].str.replace(',', '.')
lpi_2007_2022['2022'] = lpi_2007_2022['2022'].str.replace(',', '.')
# Changer le type dtype des colonnes
lpi_2007_2022[['2007', '2010', '2012', '2014', '2016', '2018', '2022']] = lpi_2007_2022[['2007', '2010', '2012', '2014', '2016', '2018', '2022']].astype(float)
lpi_2007_2022

,Country Name,Country Code,Indice de performance logistique : performance globale (1=faible et 5=élevée),2007,2010,2012,2014,2016,2018,2022,AVG
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#NUM!
1,NaN,AFE,NaN,2.368095,2.265000,2.409474,2.432728,2.528828,2.475000,2.636364,"2,432728273"
2,Afghanistan,AFG,NaN,1.250000,2.090000,2.160000,2.119709,2.145073,1.920000,2.000000,"2,09"
3,NaN,AFW,NaN,2.282778,2.301667,2.435556,2.383316,2.302738,2.316667,2.520000,"2,316666667"
4,Angola,AGO,NaN,2.500000,2.020000,2.000000,2.311173,2.310630,2.000000,2.300000,"2,3"
...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#NUM!
262,"Yémen, Rép. du",YEM,NaN,2.220000,2.350000,2.790000,2.207403,NaN,2.260000,2.600000,"2,305"
263,Afrique du Sud,ZAF,NaN,3.540000,3.590000,3.560000,3.617883,3.747822,3.190000,3.800000,"3,59"
264,Zambie,ZMB,NaN,2.440000,2.010000,NaN,2.467993,2.415493,2.480000,NaN,"2,44"
265,Zimbabwe,ZWE,NaN,2.210000,NaN,2.270000,2.498457,2.129670,2.160000,2.300000,"2,24"

In [62]:
lpi_2007_2022.drop(columns=['AVG'], inplace=True)

In [63]:
lpi_2007_2022

,Country Name,Country Code,Indice de performance logistique : performance globale (1=faible et 5=élevée),2007,2010,2012,2014,2016,2018,2022
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,AFE,NaN,2.368095,2.265000,2.409474,2.432728,2.528828,2.475000,2.636364
2,Afghanistan,AFG,NaN,1.250000,2.090000,2.160000,2.119709,2.145073,1.920000,2.000000
3,NaN,AFW,NaN,2.282778,2.301667,2.435556,2.383316,2.302738,2.316667,2.520000
4,Angola,AGO,NaN,2.500000,2.020000,2.000000,2.311173,2.310630,2.000000,2.300000
...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yémen, Rép. du",YEM,NaN,2.220000,2.350000,2.790000,2.207403,NaN,2.260000,2.600000
263,Afrique du Sud,ZAF,NaN,3.540000,3.590000,3.560000,3.617883,3.747822,3.190000,3.800000
264,Zambie,ZMB,NaN,2.440000,2.010000,NaN,2.467993,2.415493,2.480000,NaN
265,Zimbabwe,ZWE,NaN,2.210000,NaN,2.270000,2.498457,2.129670,2.160000,2.300000

In [64]:
lpi_2007_2022.drop(columns=['Indice de performance logistique : performance globale (1=faible et 5=élevée)'], inplace=True)

In [65]:
# Remplacer Nan par median
median_values = lpi_2007_2022[['2007', '2010', '2012', '2014', '2016', '2018', '2022']].median()
lpi_2007_2022[['Country Name', 'Country Code', '2007', '2010', '2012', '2014', '2016', '2018', '2022']] = lpi_2007_2022[['Country Name', 'Country Code','2007', '2010', '2012', '2014', '2016', '2018', '2022']].fillna(median_values)

# Calculer la lpi moyenne pour chaque pays
lpi_2007_2022['lpi_AVG_2007_2022'] = lpi_2007_2022[['2007', '2010', '2012', '2014', '2016', '2018', '2022']].mean(axis=1)

In [66]:
lpi_2007_2022.round(2)

,Country Name,Country Code,2007,2010,2012,2014,2016,2018,2022,lpi_AVG_2007_2022
0,Aruba,ABW,2.50,2.57,2.66,2.70,2.63,2.63,2.80,2.64
1,NaN,AFE,2.37,2.26,2.41,2.43,2.53,2.48,2.64,2.45
2,Afghanistan,AFG,1.25,2.09,2.16,2.12,2.15,1.92,2.00,1.95
3,NaN,AFW,2.28,2.30,2.44,2.38,2.30,2.32,2.52,2.36
4,Angola,AGO,2.50,2.02,2.00,2.31,2.31,2.00,2.30,2.21
...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,2.50,2.57,2.66,2.70,2.63,2.63,2.80,2.64
262,"Yémen, Rép. du",YEM,2.22,2.35,2.79,2.21,2.63,2.26,2.60,2.44
263,Afrique du Sud,ZAF,3.54,3.59,3.56,3.62,3.75,3.19,3.80,3.58
264,Zambie,ZMB,2.44,2.01,2.66,2.47,2.42,2.48,2.80,2.47
265,Zimbabwe,ZWE,2.21,2.57,2.27,2.50,2.13,2.16,2.30,2.31

In [67]:
lpi_2007_2022.drop(columns=['2007', '2010', '2012', '2014', '2016', '2018', '2022'], inplace=True)

In [68]:
lpi_2007_2022 = lpi_2007_2022.round(2)
lpi_2007_2022

       Country Name Country Code  lpi_AVG_2007_2022
0             Aruba          ABW               2.64
1               NaN          AFE               2.45
2       Afghanistan          AFG               1.95
3               NaN          AFW               2.36
4            Angola          AGO               2.21
..              ...          ...                ...
261          Kosovo          XKX               2.64
262  Yémen, Rép. du          YEM               2.44
263  Afrique du Sud          ZAF               3.58
264          Zambie          ZMB               2.47
265        Zimbabwe          ZWE               2.31

[266 rows x 3 columns]

In [69]:
lpi_2007_2022.nunique()

Country Name         264
Country Code         266
lpi_AVG_2007_2022    114
dtype: int64

In [70]:
lpi_2007_2022.describe()

       lpi_AVG_2007_2022
count         266.000000
mean            2.754586
std             0.480285
min             1.950000
25%             2.440000
50%             2.640000
75%             2.890000
max             4.190000

# **NETTOYAGE**

* **PIB par habitant en unités de devises locale constante**

In [71]:
pib_par_habitant_2021

,Country Name,Country Code,PIB par habitant (unités de devises locales constantes)
0,Aruba,ABW,"47369,42592"
1,NaN,AFE,NaN
2,Afghanistan,AFG,"27467,79994"
3,NaN,AFW,NaN
4,Angola,AGO,"42842,50181"
...,...,...,...
261,Kosovo,XKX,"3421,228664"
262,"Yémen, Rép. du",YEM,NaN
263,Afrique du Sud,ZAF,"75987,07811"
264,Zambie,ZMB,"7515,175043"
265,Zimbabwe,ZWE,"13264,82638"

In [72]:
pib_par_habitant_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Country Name                                             264 non-null    object
 1   Country Code                                             266 non-null    object
 2   PIB par habitant (unités de devises locales constantes)  207 non-null    object
dtypes: object(3)
memory usage: 6.4+ KB

In [73]:
pib_par_habitant_2021.isna().sum()

Country Name                                                2
Country Code                                                0
PIB par habitant (unités de devises locales constantes)    59
dtype: int64

In [74]:
# Renommer la colonne
pib_par_habitant_2021 = pib_par_habitant_2021.rename(columns={'PIB par habitant (unités de devises locales constantes)': 'PIB_par_habitant'})

# Remplacer les ',' par des '.'
pib_par_habitant_2021['PIB_par_habitant'] = pib_par_habitant_2021['PIB_par_habitant'].str.replace(',', '.')

# Changer le dtype
pib_par_habitant_2021['PIB_par_habitant'] = pib_par_habitant_2021['PIB_par_habitant'].astype(float)

In [75]:
pib_par_habitant_2021.round(2)

       Country Name Country Code  PIB_par_habitant
0             Aruba          ABW          47369.43
1               NaN          AFE               NaN
2       Afghanistan          AFG          27467.80
3               NaN          AFW               NaN
4            Angola          AGO          42842.50
..              ...          ...               ...
261          Kosovo          XKX           3421.23
262  Yémen, Rép. du          YEM               NaN
263  Afrique du Sud          ZAF          75987.08
264          Zambie          ZMB           7515.18
265        Zimbabwe          ZWE          13264.83

[266 rows x 3 columns]

In [76]:
pib_par_habitant_2021.describe()

       PIB_par_habitant
count      2.070000e+02
mean       2.424788e+06
std        1.341691e+07
min        4.313355e+02
25%        1.841325e+04
50%        5.871667e+04
75%        3.806321e+05
max        1.733800e+08

In [77]:
pib_par_habitant_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country Name      264 non-null    object
 1   Country Code      266 non-null    object
 2   PIB_par_habitant  207 non-null    float64
dtypes: float64(1), object(2)
memory usage: 6.4+ KB

In [78]:
# Vérifier les doublons
for column in pib_par_habitant_2021.columns:
    num_duplicates = pib_par_habitant_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country Name': 1 duplicates
Column 'Country Code': 0 duplicates
Column 'PIB_par_habitant': 58 duplicates

In [79]:
# Visualiser les lignes présentant des doublons
duplicate_rows = pib_par_habitant_2021[pib_par_habitant_2021.duplicated(subset=['Country Name'], keep=False)]
print(duplicate_rows)

  Country Name Country Code  PIB_par_habitant
1          NaN          AFE               NaN
3          NaN          AFW               NaN

# **NETTOYAGE**

* **Stabilité Politique et absence de violence**

In [80]:
stabilite_politique_2021.head()

,Country/Territory,Code,"(+2,5) : Forte stabilité politique et absence quasi-totale de violence.\n(-2,5) : Forte instabilité politique, avec une prévalence élevée de violence et de terrorisme"
0,Aruba,ABW,"1,43"
1,Andorra,ADO,"1,58"
2,Afghanistan,AFG,"-2,52"
3,Angola,AGO,"-0,71"
4,Anguilla,AIA,"1,53"

In [81]:
# Rename column
stabilite_politique_2021 = stabilite_politique_2021.rename(columns={'(+2,5) : Forte stabilité politique et absence quasi-totale de violence.\n(-2,5) : Forte instabilité politique, avec une prévalence élevée de violence et de terrorisme': 'Stabilité_Politique'})

In [82]:
stabilite_politique_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country/Territory    214 non-null    object
 1   Code                 214 non-null    object
 2   Stabilité_Politique  213 non-null    object
dtypes: object(3)
memory usage: 5.1+ KB

In [83]:
# Vérifier les doublons
for column in stabilite_politique_2021.columns:
    num_duplicates = stabilite_politique_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country/Territory': 0 duplicates
Column 'Code': 0 duplicates
Column 'Stabilité_Politique': 49 duplicates

In [84]:
stabilite_politique_2021.isna().sum()

Country/Territory      0
Code                   0
Stabilité_Politique    1
dtype: int64

In [85]:
# Remplacer les ',' par des '.'
stabilite_politique_2021['Stabilité_Politique'] = stabilite_politique_2021['Stabilité_Politique'].str.replace(',', '.')

# Changer le dtype
stabilite_politique_2021['Stabilité_Politique'] = stabilite_politique_2021['Stabilité_Politique'].astype(float)

In [86]:
stabilite_politique_2021.head()

  Country/Territory Code  Stabilité_Politique
0             Aruba  ABW                 1.43
1           Andorra  ADO                 1.58
2       Afghanistan  AFG                -2.52
3            Angola  AGO                -0.71
4          Anguilla  AIA                 1.53

In [87]:
stabilite_politique_2021.describe()

       Stabilité_Politique
count           213.000000
mean             -0.000141
std               1.000067
min              -2.730000
25%              -0.580000
50%               0.070000
75%               0.830000
max               1.880000

# **NETTOYAGE**

* **quantité_production_poulet_2021**

In [88]:
quantité_production_poulet_2021.head(2)

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2021,2021,tonnes,28480,I,Valeur imputée
1,QCL,Cultures et produits animaux,710,Afrique du Sud,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2021,2021,tonnes,1910000,A,Chiffre officiel

In [89]:
# Supprimmer les colonnes inutiles
quantité_production_poulet_2021 = quantité_production_poulet_2021.drop(columns=['Code Domaine', 'Domaine', 'Code Élément', 'Élément', 'Code Produit (CPC)', 'Produit', 'Code année', 'Année', 'Unité', 'Symbole', 'Description du Symbole'])

In [90]:
# Renommer colonne valeur
quantité_production_poulet_2021 = quantité_production_poulet_2021.rename(columns={'Valeur': 'Quantité_production_poulet_tonne'})

# Remplacer les ',' par des '.'
quantité_production_poulet_2021['Quantité_production_poulet_tonne'] = quantité_production_poulet_2021['Quantité_production_poulet_tonne'].str.replace(',', '.')

# Changer le dtype
quantité_production_poulet_2021['Quantité_production_poulet_tonne'] = quantité_production_poulet_2021['Quantité_production_poulet_tonne'].astype(float)
quantité_production_poulet_2021['Code zone (M49)'] = quantité_production_poulet_2021['Code zone (M49)'].astype(object)
quantité_production_poulet_2021.head(2)

  Code zone (M49)            Zone  Quantité_production_poulet_tonne
0               4     Afghanistan                            28480.0
1             710  Afrique du Sud                          1910000.0

In [91]:
quantité_production_poulet_2021.describe()

       Quantité_production_poulet_tonne
count                       1.950000e+02
mean                        6.962951e+05
std                         2.346015e+06
min                         0.000000e+00
25%                         8.507650e+03
50%                         6.434530e+04
75%                         2.867801e+05
max                         1.900350e+07

In [92]:
# Vérifier les doublons
for column in quantité_production_poulet_2021.columns:
    num_duplicates = quantité_production_poulet_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Code zone (M49)': 0 duplicates
Column 'Zone': 0 duplicates
Column 'Quantité_production_poulet_tonne': 0 duplicates

In [93]:
quantité_production_poulet_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 3 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Code zone (M49)                    195 non-null    object
 1   Zone                               195 non-null    object
 2   Quantité_production_poulet_tonne  195 non-null    float64
dtypes: float64(1), object(2)
memory usage: 4.7+ KB

In [94]:
quantité_production_poulet_2021

,Code zone (M49),Zone,Quantité_production_poulet_tonne
0,4,Afghanistan,28480.0
1,710,Afrique du Sud,1910000.0
2,8,Albanie,13250.0
3,12,Algérie,273520.2
4,276,Allemagne,1080000.0
...,...,...,...
190,862,Venezuela (République bolivarienne du),432395.9
191,704,Viet Nam,1277360.7
192,887,Yémen,198878.6
193,894,Zambie,50533.3
194,716,Zimbabwe,113000.0

# **NETTOYAGE**

* **taux_change_2021 (unités de devises locales par $ US, moyenne pour la période)**

In [95]:
taux_change_2021.head()

,Country Name,Country Code,"Taux de change officiel (unités de devises locales par $ US, moyenne pour la période)"
0,Aruba,ABW,"1,79"
1,NaN,AFE,NaN
2,Afghanistan,AFG,NaN
3,NaN,AFW,NaN
4,Angola,AGO,"631,4419555"

In [96]:
taux_change_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   Country Name                                                                           264 non-null    object
 1   Country Code                                                                           266 non-null    object
 2   Taux de change officiel (unités de devises locales par $ US, moyenne pour la période)  174 non-null    object
dtypes: object(3)
memory usage: 6.4+ KB

In [97]:
taux_change_2021.isna().sum()

Country Name                                                                              2
Country Code                                                                              0
Taux de change officiel (unités de devises locales par $ US, moyenne pour la période)    92
dtype: int64

In [98]:
# Renommer la colonne
taux_change_2021 = taux_change_2021.rename(columns={'Taux de change officiel (unités de devises locales par $ US, moyenne pour la période)': 'Taux_change_unit_devises_local_par_$US_Moy_period'})

In [99]:
# Remplacer les ',' par des '.'
taux_change_2021['Taux_change_unit_devises_local_par_$US_Moy_period'] = taux_change_2021['Taux_change_unit_devises_local_par_$US_Moy_period'].str.replace(',', '.')

# Changer le dtype
taux_change_2021['Taux_change_unit_devises_local_par_$US_Moy_period'] = taux_change_2021['Taux_change_unit_devises_local_par_$US_Moy_period'].astype(float)

In [100]:
taux_change_2021.head(2)

  Country Name Country Code  Taux_change_unit_devises_local_par_$US_Moy_period
0        Aruba          ABW                                               1.79
1          NaN          AFE                                                NaN

In [101]:
# Vérifier les doublons
for column in taux_change_2021.columns:
    num_duplicates = taux_change_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country Name': 1 duplicates
Column 'Country Code': 0 duplicates
Column 'Taux_change_unit_devises_local_par_$US_Moy_period': 129 duplicates

In [102]:
# Visualiser les lignes présentant des doublons
duplicate_rows = taux_change_2021[taux_change_2021.duplicated(subset=['Country Name'], keep=False)]
print(duplicate_rows)

  Country Name Country Code  Taux_change_unit_devises_local_par_$US_Moy_period
1          NaN          AFE                                                NaN
3          NaN          AFW                                                NaN

# **NETTOYAGE**

* **population_2021**

In [103]:
population_2021.head(10)

          Country Name Country Code     Indicator Name  2021 (person)
0                Aruba          ABW  Population, total       106537.0
1                  NaN          AFE  Population, total    702977106.0
2          Afghanistan          AFG  Population, total     40099462.0
3                  NaN          AFW  Population, total    478185907.0
4               Angola          AGO  Population, total     34503774.0
5              Albanie          ALB  Population, total      2811666.0
6              Andorre          AND  Population, total        79034.0
7       Le monde arabe          ARB  Population, total    456520777.0
8  Émirats arabes unis          ARE  Population, total      9365145.0
9            Argentine          ARG  Population, total     45808747.0

In [104]:
# Renommer la colonne
population_2021 = population_2021.rename(columns={'2021 (person)': 'person_2021'})

# Suppprimer les colonnes inutiles
population_2021 = population_2021.drop(columns=['Indicator Name'])

In [105]:
population_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  264 non-null    object
 1   Country Code  266 non-null    object
 2   person_2021   265 non-null    float64
dtypes: float64(1), object(2)
memory usage: 6.4+ KB

In [106]:
population_2021.head(2)

  Country Name Country Code  person_2021
0        Aruba          ABW     106537.0
1          NaN          AFE  702977106.0

In [107]:
population_2021.describe()

        person_2021
count  2.650000e+02
mean   3.206783e+08
std    9.965683e+08
min    1.120400e+04
25%    1.786038e+06
50%    1.050577e+07
75%    6.358833e+07
max    7.888964e+09

In [108]:
# Vérifier les doublons
for column in population_2021.columns:
    num_duplicates = population_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Country Name': 1 duplicates
Column 'Country Code': 0 duplicates
Column 'person_2021': 2 duplicates

In [109]:
# Visualiser les lignes présentant des doublons
duplicate_rows = population_2021[population_2021.duplicated(subset=['Country Name'], keep=False)]
print(duplicate_rows)

  Country Name Country Code  person_2021
1          NaN          AFE  702977106.0
3          NaN          AFW  478185907.0

In [110]:
# Visualiser les lignes présentant des doublons
duplicate_rows = population_2021[population_2021.duplicated(subset=['person_2021'], keep=False)]
print(duplicate_rows)

                            Country Name Country Code   person_2021
204                          Asie du Sud          SAS  1.901912e+09
217                Afrique subsaharienne          SSF  1.181163e+09
240            Asie du Sud (BIRD et IDA)          TSA  1.901912e+09
241  Afrique subsaharienne (BIRD et IDA)          TSS  1.181163e+09

# **NETTOYAGE**

* **dispo_proteine_2021**

In [111]:
dispo_proteine_2021.head(10)

   Code zone (M49)                Zone Valeur (g/personne/jour)
0                4         Afghanistan                      4,4
1              710      Afrique du Sud                     34,6
2                8             Albanie                     25,1
3               12             Algérie                      8,6
4              276           Allemagne                     32,4
5               24              Angola                      9,0
6               28  Antigua-et-Barbuda                     38,7
7              682     Arabie saoudite                     25,3
8               32           Argentine                     53,7
9               51             Arménie                     28,0

In [112]:
# Renommer les colonnes
dispo_proteine_2021 = dispo_proteine_2021.rename(columns={'Valeur (g/personne/jour)': 'Dispo_proteine_g_personne_jour', 'Code zone (M49)': 'Code_pays'})
dispo_proteine_2021.head(2)

   Code_pays            Zone Dispo_proteine_g_personne_jour
0          4     Afghanistan                            4,4
1        710  Afrique du Sud                           34,6

In [113]:
dispo_proteine_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Code_pays                       186 non-null    int64
 1   Zone                            186 non-null    object
 2   Dispo_proteine_g_personne_jour  186 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.5+ KB

In [114]:
# Remplacer les ',' par des '.'
dispo_proteine_2021['Dispo_proteine_g_personne_jour'] = dispo_proteine_2021['Dispo_proteine_g_personne_jour'].str.replace(',', '.')

# Changer le dtype
dispo_proteine_2021['Dispo_proteine_g_personne_jour'] = dispo_proteine_2021['Dispo_proteine_g_personne_jour'].astype(float)
dispo_proteine_2021['Code_pays'] = dispo_proteine_2021['Code_pays'].astype(object)

dispo_proteine_2021.head(2)

  Code_pays            Zone  Dispo_proteine_g_personne_jour
0         4     Afghanistan                             4.4
1       710  Afrique du Sud                            34.6

In [115]:
# Vérifier les doublons
for column in dispo_proteine_2021.columns:
    num_duplicates = dispo_proteine_2021[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'Code_pays': 0 duplicates
Column 'Zone': 0 duplicates
Column 'Dispo_proteine_g_personne_jour': 29 duplicates

In [116]:
dispo_proteine_2021.describe()

       Dispo_proteine_g_personne_jour
count                      186.000000
mean                        24.061828
std                         14.025455
min                          1.700000
25%                         11.775000
50%                         24.600000
75%                         33.850000
max                         72.700000

In [117]:
dispo_proteine_2021.isna().sum()

Code_pays                         0
Zone                              0
Dispo_proteine_g_personne_jour    0
dtype: int64

# **NETTOYAGE**

* **code_pays**

In [118]:
code_pays.head(10)

   Code\nnum. Code\nalpha\n-3 Nom en français\ndu pays ou territoire
0         710             ZAF                         Afrique du Sud
1         248             ALA                             Îles Åland
2           8             ALB                                Albanie
3          12             DZA                                Algérie
4         276             DEU                              Allemagne
5          20             AND                                Andorre
6          24             AGO                                 Angola
7         660             AIA                               Anguilla
8          10             ATA                            Antarctique
9          28             ATG                     Antigua-et-Barbuda

In [119]:
# Renommer les colonnes
code_pays = code_pays.rename(columns={'Code\nnum.': 'num_pays', 'Code\nalpha\n-3': 'code_pays', 'Nom en français\ndu pays ou territoire': 'pays'})
code_pays.head(2)

   num_pays code_pays            pays
0       710       ZAF  Afrique du Sud
1       248       ALA      Îles Åland

In [120]:
code_pays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   num_pays   242 non-null    int64
 1   code_pays  242 non-null    object
 2   pays       242 non-null    object
dtypes: int64(1), object(2)
memory usage: 5.8+ KB

In [121]:
code_pays.isna().sum()

num_pays     0
code_pays    0
pays         0
dtype: int64

In [122]:
# Changer le type de colonne
code_pays['num_pays'] = code_pays['num_pays'].astype(object)

In [123]:
# Vérifier les doublons
for column in code_pays.columns:
    num_duplicates = code_pays[column].duplicated().sum()
    print(f"Column '{column}': {num_duplicates} duplicates")

Column 'num_pays': 0 duplicates
Column 'code_pays': 0 duplicates
Column 'pays': 1 duplicates

In [124]:
# Visualiser les lignes présentant des doublons
duplicate_rows = code_pays[code_pays.duplicated(subset=['pays'], keep=False)]
print(duplicate_rows)

    num_pays code_pays          pays
187      663       MAF  Saint-Martin
188      534       SXM  Saint-Martin

In [125]:
# Trier les pays par ordre alphabétique
code_pays = code_pays.sort_values(by=['pays'])
code_pays.head(5)

  num_pays code_pays            pays
0      710       ZAF  Afrique du Sud
2        8       ALB         Albanie
3       12       DZA         Algérie
4      276       DEU       Allemagne
5       20       AND         Andorre

# **JOINTURE DES TABLES**

Jointure left par code pays et numéro pays & Dispo_proteine_g_personne_jour

In [126]:
# Jointure left par code pays et numéro pays et disponibilité en proteine
df = pd.merge(code_pays, dispo_proteine_2021, left_on='num_pays', right_on='Code_pays', how='left')
df.head(10)

,num_pays,code_pays,pays,Code_pays,Zone,Dispo_proteine_g_personne_jour
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6
1,8,ALB,Albanie,8,Albanie,25.1
2,12,DZA,Algérie,12,Algérie,8.6
3,276,DEU,Allemagne,276,Allemagne,32.4
4,20,AND,Andorre,NaN,NaN,NaN
5,24,AGO,Angola,24,Angola,9.0
6,660,AIA,Anguilla,NaN,NaN,NaN
7,10,ATA,Antarctique,NaN,NaN,NaN
8,28,ATG,Antigua-et-Barbuda,28,Antigua-et-Barbuda,38.7
9,682,SAU,Arabie saoudite,682,Arabie saoudite,25.3

* **Jointure left par code pays et numéro pays & population_2021**

In [127]:
# Jointure left par code pays et numéro pays & population_2021
df = pd.merge(df, population_2021, left_on='code_pays', right_on='Country Code', how='left')
df.head(10)

,num_pays,code_pays,pays,Code_pays,Zone,Dispo_proteine_g_personne_jour,Country Name,Country Code,person_2021
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0
5,24,AGO,Angola,24,Angola,9.0,Angola,AGO,34503774.0
6,660,AIA,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN
7,10,ATA,Antarctique,NaN,NaN,NaN,NaN,NaN,NaN
8,28,ATG,Antigua-et-Barbuda,28,Antigua-et-Barbuda,38.7,Antigua-et-Barbuda,ATG,93219.0
9,682,SAU,Arabie saoudite,682,Arabie saoudite,25.3,Arabie saoudite,SAU,35950396.0

* **Jointure left par code pays et numéro pays & taux_change_2021**

In [128]:
# Jointure left par code pays et numéro pays & taux_change_2021**
df = pd.merge(df, taux_change_2021, left_on='code_pays', right_on='Country Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Code_pays,Zone,Dispo_proteine_g_personne_jour,Country Name_x,Country Code_x,person_2021,Country Name_y,Country Code_y,Taux_change_unit_devises_local_par_$US_Moy_period
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0,Afrique du Sud,ZAF,14.778678
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0,Albanie,ALB,103.520000
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0,Algérie,DZA,135.064058
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0,Allemagne,DEU,NaN
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0,Andorre,AND,0.845377

* **Jointure left par code pays et numéro pays & quantité_production_poulet_2021**

In [129]:
# Jointure left par code pays et numéro pays & quantité_production_poulet_2021
df = pd.merge(df, quantité_production_poulet_2021, left_on='num_pays', right_on='Code zone (M49)', how='left')
df.head(5)

,num_pays,code_pays,pays,Code_pays,Zone_x,Dispo_proteine_g_personne_jour,Country Name_x,Country Code_x,person_2021,Country Name_y,Country Code_y,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Zone_y,Quantité_production_poulet_tonne
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0,Afrique du Sud,ZAF,14.778678,710,Afrique du Sud,1910000.0
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0,Albanie,ALB,103.520000,8,Albanie,13250.0
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0,Algérie,DZA,135.064058,12,Algérie,273520.2
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0,Allemagne,DEU,NaN,276,Allemagne,1080000.0
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0,Andorre,AND,0.845377,NaN,NaN,NaN

In [130]:
# Afficher toutes les lignes df
with pd.option_context('display.max_rows', None):
    display(df)

,num_pays,code_pays,pays,Code_pays,Zone_x,Dispo_proteine_g_personne_jour,Country Name_x,Country Code_x,person_2021,Country Name_y,Country Code_y,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Zone_y,Quantité_production_poulet_tonne
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0,Afrique du Sud,ZAF,14.778678,710,Afrique du Sud,1910000.0
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0,Albanie,ALB,103.520000,8,Albanie,13250.0
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0,Algérie,DZA,135.064058,12,Algérie,273520.2
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0,Allemagne,DEU,NaN,276,Allemagne,1080000.0
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0,Andorre,AND,0.845377,NaN,NaN,NaN
5,24,AGO,Angola,24,Angola,9.0,Angola,AGO,34503774.0,Angola,AGO,631.441955,24,Angola,55384.7
6,660,AIA,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10,ATA,Antarctique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28,ATG,Antigua-et-Barbuda,28,Antigua-et-Barbuda,38.7,Antigua-et-Barbuda,ATG,93219.0,Antigua-et-Barbuda,ATG,2.700000,28,Antigua-et-Barbuda,33.6
9,682,SAU,Arabie saoudite,682,Arabie saoudite,25.3,Arabie saoudite,SAU,35950396.0,Arabie saoudite,SAU,3.750000,682,Arabie saoudite,930000.0
10,32,ARG,Argentine,32,Argentine,53.7,Argentine,ARG,45808747.0,Argentine,ARG,94.990742,32,Argentine,2294101.4
11,51,ARM,Arménie,51,Arménie,28.0,Arménie,ARM,2790974.0,Arménie,ARM,503.769675,51,Arménie,14600.0
12,533,ABW,Aruba,NaN,NaN,NaN,Aruba,ABW,106537.0,Aruba,ABW,1.790000,NaN,NaN,NaN
13,36,AUS,Australie,36,Australie,48.2,Australie,AUS,25685412.0,Australie,AUS,1.331224,36,Australie,1292240.0
14,40,AUT,Autriche,40,Autriche,33.4,Autriche,AUT,8955797.0,Autriche,AUT,NaN,40,Autriche,129390.0
15,31,AZE,Azerbaïdjan,31,Azerbaïdjan,18.2,Azerbaïdjan,AZE,10137750.0,Azerbaïdjan,AZE,1.700000,31,Azerbaïdjan,124388.0
16,44,BHS,Bahamas,44,Bahamas,48.9,Bahamas,BHS,407906.0,Bahamas,BHS,1.000000,44,Bahamas,6138.0
17,48,BHR,Bahreïn,48,Bahreïn,39.0,Bahreïn,BHR,1463265.0,Bahreïn,BHR,0.376000,48,Bahreïn,8262.0
18,50,BGD,Bangladesh,50,Bangladesh,2.2,Bangladesh,BGD,169356251.0,Bangladesh,BGD,85.083763,50,Bangladesh,215838.4
19,52,BRB,Barbade,52,Barbade,37.5,Barbade,BRB,281200.0,Barbade,BRB,2.000000,52,Barbade,13183.0
20,56,BEL,Belgique,56,Belgique,31.3,Belgique,BEL,11586195.0,Belgique,BEL,NaN,56,Belgique,447710.0
21,84,BLZ,Belize,84,Belize,23.9,Belize,BLZ,400031.0,Belize,BLZ,2.000000,84,Belize,19187.0
22,60,BMU,Bermudes,NaN,NaN,NaN,Bermudes,BMU,63764.0,Bermudes,BMU,1.000000,NaN,NaN,NaN
23,64,BTN,Bhoutan,64,Bhoutan,6.3,Bhoutan,BTN,777486.0,Bhoutan,BTN,73.918013,64,Bhoutan,1865.5
24,104,MMR,Birmanie,104,Myanmar,8.9,Myanmar,MMR,53798084.0,Myanmar,MMR,NaN,104,Myanmar,620000.0
25,112,BLR,Biélorussie,112,Bélarus,41.3,Bélarus,BLR,9302585.0,Bélarus,BLR,2.538675,112,Bélarus,503200.0
26,68,BOL,Bolivie,68,Bolivie (État plurinational de),35.1,Bolivie,BOL,12079472.0,Bolivie,BOL,6.910000,68,Bolivie (État plurinational de),506148.1
27,70,BIH,Bosnie-Herzégovine,70,Bosnie-Herzégovine,20.7,Bosnie-Herzégovine,BIH,3270943.0,Bosnie-Herzégovine,BIH,1.653606,70,Bosnie-Herzégovine,63703.0
28,72,BWA,Botswana,72,Botswana,15.9,Botswana,BWA,2588423.0,Botswana,BWA,11.087258,72,Botswana,1266.8
29,96,BRN,Brunei,NaN,NaN,NaN,Brunéi Darussalam,BRN,445373.0,Brunéi Darussalam,BRN,1.343807,96,Brunéi Darussalam,31444.6
30,76,BRA,Brésil,76,Brésil,44.4,Brésil,BRA,214326223.0,Brésil,BRA,5.394401,76,Brésil,14329000.0
31,100,BGR,Bulgarie,100,Bulgarie,27.5,Bulgarie,BGR,6877743.0,Bulgarie,BGR,1.653775,100,Bulgarie,90680.0
32,854,BFA,Burkina Faso,854,Burkina Faso,15.1,Burkina Faso,BFA,22100683.0,Burkina Faso,BFA,554.530675,854,Burkina Faso,149121.0
33,108,BDI,Burundi,108,Burundi,1.7,Burundi,BDI,12551213.0,Burundi,BDI,1975.950881,108,Burundi,8228.5
34,204,BEN,Bénin,204,Bénin,7.5,Bénin,BEN,12996895.0,Bénin,BEN,554.607799,204,Bénin,9359.4
35,116,KHM,Cambodge,116,Cambodge,5.8,Cambodge,KHM,16589023.0,Cambodge,KHM,4098.722795,116,Cambodge,16296.8
36,120,CMR,Cameroun,120,Cameroun,6.9,Cameroun,CMR,27198628.0,Cameroun,CMR,554.530675,120,Cameroun,104762.1
37,124,CAN,Canada,124,Canada,37.2,Canada,CAN,38239864.0,Canada,CAN,1.253877,124,Canada,1334020.0
38,132,CPV,Cap-Vert,132,Cabo Verde,17.6,Cabo Verde,CPV,587925.0,Cabo Verde,CPV,93.218092,132,Cabo Verde,581.4
39,152,CHL,Chili,152,Chili,41.7,Chili,CHL,19493184.0,Chili,CHL,758.955379,152,Chili,680289.5
40,196,CYP,Chypre,196,Chypre,30.3,Chypre,CYP,1244188.0,Chypre,CYP,NaN,196,Chypre,26640.0
41,170,COL,Colombie,170,Colombie,27.4,Colombie,COL,51516562.0,Colombie,COL,3744.244167,170,Colombie,1694334.9
42,174,COM,Comores,174,Comores,16.1,Comores,COM,821625.0,Comores,COM,415.955849,174,Comores,585.0
43,408,PRK,Corée du Nord,408,République populaire démocratique de Corée,6.0,"Corée, République démocratique de",PRK,25971909.0,"Corée, République démocratique de",PRK,NaN,408,République populaire démocratique de Corée,30902.2
44,410,KOR,Corée du Sud,410,République de Corée,34.6,"Corée, République de",KOR,51769539.0,"Corée, République de",KOR,1143.951667,410,République de Corée,935000.0
45,188,CRI,Costa Rica,188,Costa Rica,26.7,Costa Rica,CRI,5153957.0,Costa Rica,CRI,620.784720,188,Costa Rica,147816.0
46,191,HRV,Croatie,191,Croatie,36.9,Croatie,HRV,3878981.0,Croatie,HRV,6.360083,191,Croatie,58610.0
47,192,CUB,Cuba,192,Cuba,23.2,Cuba,CUB,11256372.0,Cuba,CUB,NaN,192,Cuba,17918.0
48,531,CUW,Curaçao,NaN,NaN,NaN,Curacao,CUW,152369.0,Curacao,CUW,1.790000,NaN,NaN,NaN
49,384,CIV,Côte d'Ivoire,384,Côte d'Ivoire,8.5,Côte d'Ivoire,CIV,27478249.0,Côte d'Ivoire,CIV,554.530675,384,Côte d'Ivoire,63949.0
50,208,DNK,Danemark,208,Danemark,28.9,Danemark,DNK,5856733.0,Danemark,DNK,6.287113,208,Danemark,163100.0
51,262,DJI,Djibouti,262,Djibouti,7.4,Djibouti,DJI,1105557.0,Djibouti,DJI,177.721000,NaN,NaN,NaN
52,212,DMA,Dominique,212,Dominique,36.8,Dominique,DMA,72412.0,Dominique,DMA,2.700000,212,Dominique,369.4
53,724,ESP,Espagne,724,Espagne,42.1,Espagne,ESP,47415794.0,Espagne,ESP,NaN,724,Espagne,1331410.0
54,233,EST,Estonie,233,Estonie,27.9,Estonie,EST,1330932.0,Estonie,EST,NaN,233,Estonie,23300.0
55,748,SWZ,Eswatini,748,Eswatini,12.7,Eswatini,SWZ,1192271.0,Eswatini,SWZ,14.783435,748,Eswatini,5520.6
56,242,FJI,Fidji,242,Fidji,20.8,Fidji,FJI,924610.0,Fidji,FJI,2.070633,242,Fidji,25715.0
57,246,FIN,Finlande,246,Finlande,32.5,Finlande,FIN,5541017.0,Finlande,FIN,NaN,246,Finlande,138600.0
58,250,FRA,France,250,France,38.3,France,FRA,67764304.0,France,FRA,NaN,250,France,1143000.0
59,266,GAB,Gabon,266,Gabon,33.5,Gabon,GAB,2341179.0,Gabon,GAB,554.530675,266,Gabon,4111.4
60,270,GMB,Gambie,270,Gambie,7.4,Gambie,GMB,2639916.0,Gambie,GMB,51.484444,270,Gambie,1098.6
61,288,GHA,Ghana,288,Ghana,11.2,Ghana,GHA,32833031.0,Ghana,GHA,5.805700,288,Ghana,65190.0
62,292,GIB,Gibraltar,NaN,NaN,NaN,Gibraltar,GIB,32669.0,Gibraltar,GIB,0.727065,NaN,NaN,NaN
63,308,GRD,Grenade,308,Grenade,35.7,Grenade,GRD,124610.0,Grenade,GRD,2.700000,308,Grenade,421.2
64,304,GRL,Groenland,NaN,NaN,NaN,Groenland,GRL,56653.0,Groenland,GRL,NaN,NaN,NaN,NaN
65,300,GRC,Grèce,300,Grèce,31.6,Grèce,GRC,10569207.0,Grèce,GRC,NaN,300,Grèce,235500.0
66,312,GLP,Guadeloupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,316,GUM,Guam,NaN,NaN,NaN,Guam,GUM,170534.0,Guam,GUM,NaN,NaN,NaN,NaN
68,320,GTM,Guatemala,320,Guatemala,18.9,Guatemala,GTM,17109746.0,Guatemala,GTM,7.734388,320,Guatemala,342169.0
69,831,GGY,Guernesey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,324,GIN,Guinée,324,Guinée,8.2,Guinée,GIN,13531906.0,Guinée,GIN,NaN,324,Guinée,14996.9
71,226,GNQ,Guinée équatoriale,NaN,NaN,NaN,Guinée équatoriale,GNQ,1634466.0,Guinée équatoriale,GNQ,554.530675,226,Guinée équatoriale,260.3
72,624,GNB,Guinée-Bissau,624,Guinée-Bissau,6.7,Guinée-Bissau,GNB,2060721.0,Guinée-Bissau,GNB,554.530675,624,Guinée-Bissau,3076.9
73,328,GUY,Guyana,328,Guyana,32.4,Guyana,GUY,804567.0,Guyana,GUY,208.500000,328,Guyana,48945.0
74,254,GUF,Guyane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,268,GEO,Géorgie,268,Géorgie,17.3,Géorgie,GEO,3708610.0,Géorgie,GEO,3.221558,268,Géorgie,25000.0
76,239,SGS,Géorgie du Sud-et-les îles Sandwich du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,332,HTI,Haïti,332,Haïti,10.5,Haïti,HTI,11447569.0,Haïti,HTI,89.226637,332,Haïti,8753.3
78,340,HND,Honduras,340,Honduras,17.4,Honduras,HND,10278345.0,Honduras,HND,24.016655,340,Honduras,243580.7
79,344,HKG,Hong Kong,344,Chine - RAS de Hong-Kong,72.7,"Chine, RAS de Hong Kong",HKG,7413100.0,"Chine, RAS de Hong Kong",HKG,7.773250,344,Chine - RAS de Hong-Kong,25550.9
80,348,HUN,Hongrie,348,Hongrie,32.7,Hongrie,HUN,9709891.0,Hongrie,HUN,303.140833,348,Hongrie,367610.0
81,368,IRQ,Irak,368,Iraq,8.5,Iraq,IRQ,43533592.0,Iraq,IRQ,1450.000000,368,Iraq,144702.0
82,372,IRL,Irlande,372,Irlande,40.7,Irlande,IRL,5033164.0,Irlande,IRL,NaN,372,Irlande,147770.0
83,352,ISL,Islande,352,Islande,42.6,Islande,ISL,372520.0,Islande,ISL,126.988860,352,Islande,8997.0
84,376,ISR,Israël,376,Israël,49.1,Israël,ISR,9371400.0,Israël,ISR,3.230198,376,Israël,541292.0
85,380,ITA,Italie,380,Italie,31.3,Italie,ITA,59133173.0,Italie,ITA,NaN,380,Italie,1068500.0
86,388,JAM,Jamaïque,388,Jamaïque,29.5,Jamaïque,JAM,2827695.0,Jamaïque,JAM,150.790106,388,Jamaïque,125192.0
87,392,JPN,Japon,392,Japon,25.4,Japon,JPN,125681593.0,Japon,JPN,109.754324,392,Japon,2342999.8
88,832,JEY,Jersey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,400,JOR,Jordanie,400,Jordanie,16.6,Jordanie,JOR,11148278.0,Jordanie,JOR,0.710000,400,Jordanie,246582.0
90,398,KAZ,Kazakhstan,398,Kazakhstan,33.9,Kazakhstan,KAZ,19191356.0,Kazakhstan,KAZ,425.907500,398,Kazakhstan,263560.5
91,404,KEN,Kenya,404,Kenya,5.1,Kenya,KEN,53005614.0,Kenya,KEN,109.637747,404,Kenya,89450.0
92,417,KGZ,Kirghizistan,417,Kirghizistan,19.5,République kirghize,KGZ,6773400.0,République kirghize,KGZ,84.640822,417,Kirghizistan,11069.0
93,296,KIR,Kiribati,296,Kiribati,23.5,Kiribati,KIR,128874.0,Kiribati,KIR,1.331224,296,Kiribati,991.0
94,414,KWT,Koweït,414,Koweït,38.1,Koweït,KWT,4250114.0,Koweït,KWT,0.301643,414,Koweït,64345.3
95,638,REU,La Réunion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,418,LAO,Laos,418,République démocratique populaire lao,13.9,République démocratique populaire lao,LAO,7425057.0,République démocratique populaire lao,LAO,9697.915789,418,République démocratique populaire lao,36417.4
97,426,LSO,Lesotho,426,Lesotho,10.9,Lesotho,LSO,2281454.0,Lesotho,LSO,14.778678,426,Lesotho,1060.1
98,428,LVA,Lettonie,428,Lettonie,31.2,Lettonie,LVA,1884490.0,Lettonie,LVA,NaN,428,Lettonie,35080.0
99,422,LBN,Liban,422,Liban,16.3,Liban,LBN,5592631.0,Liban,LBN,1507.500000,422,Liban,126642.4
100,430,LBR,Liberia,430,Libéria,11.2,Libéria,LBR,5193416.0,Libéria,LBR,166.153701,430,Libéria,14336.7
101,434,LBY,Libye,434,Libye,25.2,Libye,LBY,6735277.0,Libye,LBY,4.514425,434,Libye,131084.7
102,438,LIE,Liechtenstein,NaN,NaN,NaN,Liechtenstein,LIE,39039.0,Liechtenstein,LIE,NaN,NaN,NaN,NaN
103,440,LTU,Lituanie,440,Lituanie,40.1,Lituanie,LTU,2800839.0,Lituanie,LTU,NaN,440,Lituanie,85030.0
104,442,LUX,Luxembourg,442,Luxembourg,36.7,Luxembourg,LUX,640064.0,Luxembourg,LUX,NaN,442,Luxembourg,0.0
105,446,MAC,Macao,446,Chine - RAS de Macao,47.8,"Région administrative spéciale de Macao, Chine",MAC,686607.0,"Région administrative spéciale de Macao, Chine",MAC,8.005532,446,Chine - RAS de Macao,3216.7
106,807,MKD,Macédoine du Nord,807,Macédoine du Nord,19.3,Macédoine du Nord,MKD,1837114.0,Macédoine du Nord,MKD,52.102158,807,Macédoine du Nord,1695.0
107,450,MDG,Madagascar,450,Madagascar,2.5,Madagascar,MDG,28915653.0,Madagascar,MDG,3829.977849,450,Madagascar,52991.4
108,458,MYS,Malaisie,458,Malaisie,28.7,Malaisie,MYS,33573874.0,Malaisie,MYS,4.143298,458,Malaisie,1583219.5
109,454,MWI,Malawi,454,Malawi,12.0,Malawi,MWI,19889742.0,Malawi,MWI,NaN,454,Malawi,143705.3
110,462,MDV,Maldives,462,Maldives,12.5,Maldives,MDV,521457.0,Maldives,MDV,15.372698,NaN,NaN,NaN
111,466,MLI,Mali,466,Mali,3.8,Mali,MLI,21904983.0,Mali,MLI,554.530675,466,Mali,59780.0
112,238,FLK,Malouines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,470,MLT,Malte,470,Malte,28.1,Malte,MLT,518536.0,Malte,MLT,NaN,470,Malte,4070.0
114,504,MAR,Maroc,504,Maroc,15.6,Maroc,MAR,37076584.0,Maroc,MAR,8.988484,504,Maroc,525000.0
115,474,MTQ,Martinique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,480,MUS,Maurice,480,Maurice,24.8,Maurice,MUS,1266334.0,Maurice,MUS,41.692133,480,Maurice,49100.0
117,478,MRT,Mauritanie,478,Mauritanie,16.2,Mauritanie,MRT,4614974.0,Mauritanie,MRT,36.063333,478,Mauritanie,3992.5
118,175,MYT,Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,484,MEX,Mexique,484,Mexique,34.9,Mexique,MEX,126705138.0,Mexique,MEX,20.272408,484,Mexique,3668551.3
120,498,MDA,Moldavie,498,République de Moldova,26.5,Moldova,MDA,2595809.0,Moldova,MDA,17.680466,498,République de Moldova,51599.9
121,492,MCO,Monaco,NaN,NaN,NaN,Monaco,MCO,36686.0,Monaco,MCO,NaN,NaN,NaN,NaN
122,496,MNG,Mongolie,496,Mongolie,64.7,Mongolie,MNG,3347782.0,Mongolie,MNG,2849.288615,496,Mongolie,245.8
123,500,MSR,Montserrat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,499,MNE,Monténégro,499,Monténégro,36.6,Monténégro,MNE,619211.0,Monténégro,MNE,0.845377,499,Monténégro,1332.7
125,508,MOZ,Mozambique,508,Mozambique,4.6,Mozambique,MOZ,32077072.0,Mozambique,MOZ,65.465000,508,Mozambique,135708.0
126,516,NAM,Namibie,516,Namibie,18.4,Namibie,NAM,2530151.0,Namibie,NAM,14.778675,516,Namibie,11663.2
127,520,NRU,Nauru,520,Nauru,54.8,Nauru,NRU,12511.0,Nauru,NRU,1.331224,520,Nauru,4.0
128,558,NIC,Nicaragua,558,Nicaragua,14.4,Nicaragua,NIC,6850540.0,Nicaragua,NIC,35.171017,558,Nicaragua,143283.0
129,562,NER,Niger,562,Niger,4.1,Niger,NER,25252722.0,Niger,NER,554.530675,562,Niger,20206.7
130,566,NGA,Nigeria,566,Nigéria,3.3,Nigéria,NGA,213401323.0,Nigéria,NGA,401.152029,566,Nigéria,342959.3
131,570,NIU,Niue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,570,Nioué,24.8
132,578,NOR,Norvège,578,Norvège,31.2,Norvège,NOR,5408320.0,Norvège,NOR,8.590000,578,Norvège,106043.0
133,540,NCL,Nouvelle-Calédonie,540,Nouvelle-Calédonie,39.0,Nouvelle-Calédonie,NCL,270390.0,Nouvelle-Calédonie,NCL,100.880223,540,Nouvelle-Calédonie,888.0
134,554,NZL,Nouvelle-Zélande,554,Nouvelle-Zélande,37.9,Nouvelle-Zélande,NZL,5111300.0,Nouvelle-Zélande,NZL,1.413800,554,Nouvelle-Zélande,224397.0
135,524,NPL,Népal,524,Népal,9.3,Népal,NPL,30034989.0,Népal,NPL,118.134082,524,Népal,226959.0
136,512,OMN,Oman,512,Oman,22.5,Oman,OMN,4520471.0,Oman,OMN,0.384500,512,Oman,6563.9
137,800,UGA,Ouganda,800,Ouganda,4.8,Ouganda,UGA,45853778.0,Ouganda,UGA,3587.051707,800,Ouganda,69340.3
138,860,UZB,Ouzbékistan,860,Ouzbékistan,19.7,Ouzbékistan,UZB,34915100.0,Ouzbékistan,UZB,10609.464390,860,Ouzbékistan,123600.0
139,586,PAK,Pakistan,586,Pakistan,9.5,Pakistan,PAK,231402117.0,Pakistan,PAK,162.906254,586,Pakistan,1809000.0
140,585,PLW,Palaos,NaN,NaN,NaN,Palaos,PLW,18024.0,Palaos,PLW,1.000000,NaN,NaN,NaN
141,275,PSE,Palestine,NaN,NaN,NaN,Cisjordanie et Gaza,PSE,4922749.0,Cisjordanie et Gaza,PSE,NaN,275,Palestine,37625.5
142,591,PAN,Panama,591,Panama,39.3,Panama,PAN,4351267.0,Panama,PAN,1.000000,591,Panama,197594.0
143,598,PNG,Papouasie-Nouvelle-Guinée,598,Papouasie-Nouvelle-Guinée,29.0,Papouasie-Nouvelle-Guinée,PNG,9949437.0,Papouasie-Nouvelle-Guinée,PNG,3.508772,598,Papouasie-Nouvelle-Guinée,6708.4
144,600,PRY,Paraguay,600,Paraguay,17.3,Paraguay,PRY,6703799.0,Paraguay,PRY,6774.162735,600,Paraguay,75054.5
145,528,NLD,Pays-Bas,528,Pays-Bas (Royaume des),31.2,Pays-Bas,NLD,17533044.0,Pays-Bas,NLD,NaN,528,Pays-Bas (Royaume des),869380.0
146,535,BES,Pays-Bas caribéens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,608,PHL,Philippines,608,Philippines,15.9,Philippines,PHL,113880328.0,Philippines,PHL,49.254598,608,Philippines,1343496.3
148,616,POL,Pologne,616,Pologne,41.4,Pologne,POL,37747124.0,Pologne,POL,3.861917,616,Pologne,2096770.0
149,258,PYF,Polynésie française,258,Polynésie française,41.8,Polynésie française,PYF,304032.0,Polynésie française,PYF,100.880223,258,Polynésie française,591.3
150,630,PRI,Porto Rico,NaN,NaN,NaN,Porto Rico,PRI,3262693.0,Porto Rico,PRI,NaN,630,Porto Rico,24479.0
151,620,PRT,Portugal,620,Portugal,40.9,Portugal,PRT,10361831.0,Portugal,PRT,NaN,620,Portugal,300040.0
152,604,PER,Pérou,604,Pérou,25.3,Pérou,PER,33715471.0,Pérou,PER,3.880554,604,Pérou,1751607.8
153,634,QAT,Qatar,634,Qatar,37.4,Qatar,QAT,2688235.0,Qatar,QAT,3.640000,634,Qatar,35344.0
154,642,ROU,Roumanie,642,Roumanie,28.8,Roumanie,ROU,19122059.0,Roumanie,ROU,4.160417,642,Roumanie,451850.0
155,826,GBR,Royaume-Uni,826,Royaume-Uni de Grande-Bretagne et d'Irlande du...,36.2,Royaume-Uni,GBR,67026292.0,Royaume-Uni,GBR,0.727065,826,Royaume-Uni de Grande-Bretagne et d'Irlande du...,1841000.0
156,643,RUS,Russie,643,Fédération de Russie,34.8,Fédération de Russie,RUS,144746762.0,Fédération de Russie,RUS,73.654350,643,Fédération de Russie,4617338.0
157,646,RWA,Rwanda,646,Rwanda,3.7,Rwanda,RWA,13461888.0,Rwanda,RWA,988.624807,646,Rwanda,13457.7
158,732,ESH,République arabe sahraouie démocratique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,140,CAF,République centrafricaine,140,République centrafricaine,17.6,République centrafricaine,CAF,5457154.0,République centrafricaine,CAF,554.530675,140,République centrafricaine,6444.4
160,214,DOM,République dominicaine,214,République dominicaine,24.4,République dominicaine,DOM,11117873.0,République dominicaine,DOM,57.221117,214,République dominicaine,347491.6
161,178,COG,République du Congo,178,Congo,22.6,"Congo, République du",COG,5835806.0,"Congo, République du",COG,554.530675,178,Congo,6883.8
162,180,COD,République démocratique du Congo,180,République démocratique du Congo,2.3,"Congo, République démocratique du",COD,95894118.0,"Congo, République démocratique du",COD,1989.391471,180,République démocratique du Congo,10532.0
163,652,BLM,Saint-Barthélemy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,659,KNA,Saint-Christophe-et-Niévès,659,Saint-Kitts-et-Nevis,43.3,Saint-Kitts-et-Nevis,KNA,47606.0,Saint-Kitts-et-Nevis,KNA,2.700000,659,Saint-Kitts-et-Nevis,16.5
165,674,SMR,Saint-Marin,NaN,NaN,NaN,Saint-Marin,SMR,33745.0,Saint-Marin,SMR,0.845377,NaN,NaN,NaN
166,534,SXM,Saint-Martin,NaN,NaN,NaN,Sint Maarten (Dutch part),SXM,40708.0,Sint Maarten (Dutch part),SXM,1.790000,NaN,NaN,NaN
167,663,MAF,Saint-Martin,NaN,NaN,NaN,Saint-Martin (fr),MAF,31948.0,Saint-Martin (fr),MAF,NaN,NaN,NaN,NaN
168,666,SPM,Saint-Pierre-et-Miquelon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,336,VAT,Saint-Siège (État de la Cité du Vatican),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,670,VCT,Saint-Vincent-et-les-Grenadines,670,Saint-Vincent-et-les Grenadines,48.9,Saint-Vincent-et-les Grenadines,VCT,104332.0,Saint-Vincent-et-les Grenadines,VCT,2.700000,670,Saint-Vincent-et-les Grenadines,452.7
171,654,SHN,"Sainte-Hélène, Ascension et Tristan da Cunha",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,662,LCA,Sainte-Lucie,662,Sainte-Lucie,48.1,Sainte-Lucie,LCA,179651.0,Sainte-Lucie,LCA,2.700000,662,Sainte-Lucie,1366.3
173,222,SLV,Salvador,222,El Salvador,19.2,El Salvador,SLV,6314167.0,El Salvador,SLV,1.000000,222,El Salvador,155405.5
174,882,WSM,Samoa,882,Samoa,47.4,Samoa,WSM,218764.0,Samoa,WSM,2.556092,882,Samoa,403.3
175,16,ASM,Samoa américaines,NaN,NaN,NaN,Samoa américaines,ASM,45035.0,Samoa américaines,ASM,NaN,NaN,NaN,NaN
176,678,STP,Sao Tomé-et-Principe,678,Sao Tomé-et-Principe,12.3,Sao Tomé-et-Principe,STP,223107.0,Sao Tomé-et-Principe,STP,20.710402,678,Sao Tomé-et-Principe,701.2
177,688,SRB,Serbie,688,Serbie,33.1,Serbie,SRB,6834326.0,Serbie,SRB,99.395942,688,Serbie,110528.0
178,690,SYC,Seychelles,690,Seychelles,32.2,Seychelles,SYC,99258.0,Seychelles,SYC,16.920523,690,Seychelles,1470.2
179,694,SLE,Sierra Leone,694,Sierra Leone,5.6,Sierra Leone,SLE,8420641.0,Sierra Leone,SLE,10.439425,694,Sierra Leone,19748.0
180,702,SGP,Singapour,NaN,NaN,NaN,Singapour,SGP,5453566.0,Singapour,SGP,1.343483,702,Singapour,75962.0
181,703,SVK,Slovaquie,703,Slovaquie,25.7,République slovaque,SVK,5447247.0,République slovaque,SVK,NaN,NaN,NaN,NaN

* **Jointure left par code pays et numéro pays & stabilité_politique_2021**

In [131]:
# Jointure left par code pays et numéro pays & stabilite_politique_2021
df = pd.merge(df, stabilite_politique_2021, left_on='code_pays', right_on='Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Code_pays,Zone_x,Dispo_proteine_g_personne_jour,Country Name_x,Country Code_x,person_2021,Country Name_y,Country Code_y,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Zone_y,Quantité_production_poulet_tonne,Country/Territory,Code,Stabilité_Politique
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0,Afrique du Sud,ZAF,14.778678,710,Afrique du Sud,1910000.0,South Africa,ZAF,-0.75
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0,Albanie,ALB,103.520000,8,Albanie,13250.0,Albania,ALB,0.20
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0,Algérie,DZA,135.064058,12,Algérie,273520.2,Algeria,DZA,-0.99
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0,Allemagne,DEU,NaN,276,Allemagne,1080000.0,Germany,DEU,0.73
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0,Andorre,AND,0.845377,NaN,NaN,NaN,NaN,NaN,NaN

* **Jointure left par code pays et numéro pays & pib_par_habitant_2021**

In [132]:
# Jointure left par code pays et numéro pays & pib_par_habitant_2021
df = pd.merge(df, pib_par_habitant_2021, left_on='code_pays', right_on='Country Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Code_pays,Zone_x,Dispo_proteine_g_personne_jour,Country Name_x,Country Code_x,person_2021,Country Name_y,...,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Zone_y,Quantité_production_poulet_tonne,Country/Territory,Code,Stabilité_Politique,Country Name,Country Code,PIB_par_habitant
0,710,ZAF,Afrique du Sud,710,Afrique du Sud,34.6,Afrique du Sud,ZAF,59392255.0,Afrique du Sud,...,14.778678,710,Afrique du Sud,1910000.0,South Africa,ZAF,-0.75,Afrique du Sud,ZAF,75987.07811
1,8,ALB,Albanie,8,Albanie,25.1,Albanie,ALB,2811666.0,Albanie,...,103.520000,8,Albanie,13250.0,Albania,ALB,0.20,Albanie,ALB,577828.56830
2,12,DZA,Algérie,12,Algérie,8.6,Algérie,DZA,44177969.0,Algérie,...,135.064058,12,Algérie,273520.2,Algeria,DZA,-0.99,Algérie,DZA,515395.95730
3,276,DEU,Allemagne,276,Allemagne,32.4,Allemagne,DEU,83196078.0,Allemagne,...,NaN,276,Allemagne,1080000.0,Germany,DEU,0.73,Allemagne,DEU,38665.63686
4,20,AND,Andorre,NaN,NaN,NaN,Andorre,AND,79034.0,Andorre,...,0.845377,NaN,NaN,NaN,NaN,NaN,NaN,Andorre,AND,32545.48675

In [133]:
# Supprimer les colonnes inutiles
df = df.drop(columns=['Code_pays', 'Zone_x', 'Country Name_x', 'Country Code_x', 'Country/Territory', 'Country Name', 'Country Code', 'Country Name_y', 'Country Code_y', 'Zone_y', 'Code'])
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675

* **Jointure left par code pays et numéro pays & lpi_2007_2022**

In [134]:
# Jointure left par code pays et numéro pays & lpi_2007_2022
df = pd.merge(df, lpi_2007_2022, left_on='code_pays', right_on='Country Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,Country Name,Country Code,lpi_AVG_2007_2022
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,Afrique du Sud,ZAF,3.58
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,Albanie,ALB,2.44
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,Algérie,DZA,2.33
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,Allemagne,DEU,4.19
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,Andorre,AND,2.64

* **Jointure left par code pays et numéro pays & inflation_2021**

In [135]:
# Jointure left par code pays et numéro pays & inflation_2021
df = pd.merge(df, inflation_2021, left_on='code_pays', right_on='Country Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,Country Name_x,Country Code_x,lpi_AVG_2007_2022,Country Name_y,Country Code_y,Inflation_prix_à_la consommation_%_annuel
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,Afrique du Sud,ZAF,3.58,Afrique du Sud,ZAF,4.611672
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,Albanie,ALB,2.44,Albanie,ALB,2.041472
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,Algérie,DZA,2.33,Algérie,DZA,7.226063
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,Allemagne,DEU,4.19,Allemagne,DEU,3.066667
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,Andorre,AND,2.64,Andorre,AND,NaN

In [136]:
# Supprimer les colonnes inutiles
df = df.drop(columns=['Country Name_y', 'Country Code_y', 'Country Name_x', 'Country Code_x'])
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN

* **Jointure left par code pays et numéro pays & governance_2021**

In [137]:
# Jointure left par code pays et numéro pays & governance_2021
df = pd.merge(df, governance_2021, left_on='code_pays', right_on='Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Country,Code,Governance_Performance
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672,South Africa,ZAF,-0.07
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472,Albania,ALB,-0.04
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063,Algeria,DZA,-0.65
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667,Germany,DEU,1.29
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN,NaN,NaN,NaN

In [138]:
# Supprimer les colonnes inutiles
df = df.drop(columns=['Country', 'Code'])
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672,-0.07
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472,-0.04
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063,-0.65
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667,1.29
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN,NaN

* **Jointure left par code pays et numéro pays & cost_animal_source_food_2021**

In [139]:
# Jointure left par code pays et numéro pays & cost_animal_source_food_2021
df = pd.merge(df, cost_animal_source_food_2021, left_on='num_pays', right_on='Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance,Code,Country,Cost of animal source foods valeur \n(PPP dollar per person per day)
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672,-0.07,710,Afrique du Sud,1.1
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472,-0.04,8,Albanie,1.2
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063,-0.65,12,Algérie,1.3
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667,1.29,276,Allemagne,0.7
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN,NaN,20,Andorre,NaN

* **Jointure left par code pays et numéro pays & controle corruption**

In [140]:
# Jointure left par code pays et numéro pays & corruption_control
df = pd.merge(df, corruption_control, left_on='code_pays', right_on='Code', how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance,Code_x,Country_x,Cost of animal source foods valeur \n(PPP dollar per person per day),Country_y,Code_y,Corruption_Value
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672,-0.07,710,Afrique du Sud,1.1,South Africa,ZAF,-0.03
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472,-0.04,8,Albanie,1.2,Albania,ALB,-0.58
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063,-0.65,12,Algérie,1.3,Algeria,DZA,-0.64
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667,1.29,276,Allemagne,0.7,Germany,DEU,1.78
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN,NaN,20,Andorre,NaN,NaN,NaN,NaN

* **Jointure left par code pays et numéro pays & epi_total**

In [141]:
# Jointure left par code pays et numéro pays & epi_total
df = pd.merge(df, epi_total, left_on=['num_pays', 'code_pays'], right_on=['code', 'iso'], how='left')
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,...,Code_y,Corruption_Value,code,iso,country,EPI.2018,EPI.2020,EPI.2022,moyenne_epi,mediane_epi
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,...,ZAF,-0.03,710.0,ZAF,South Africa,44.73,43.1,37.2,41.68,43.1
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,...,ALB,-0.58,8.0,ALB,Albania,65.46,49.0,47.1,53.85,49.0
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,...,DZA,-0.64,12.0,DZA,Algeria,57.18,44.8,29.6,43.86,44.8
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,...,DEU,1.78,276.0,DEU,Germany,78.37,77.2,62.4,72.66,77.2
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
# Supprimer les colonnes inutiles
df = df.drop(columns=['moyenne_epi', 'EPI.2022', 'EPI.2020', 'EPI.2018', 'country', 'iso', 'code', 'Code_y', 'Country_y', 'Country_x', 'Code_x'])
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance,Cost of animal source foods valeur \n(PPP dollar per person per day),Corruption_Value,mediane_epi
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,75987.07811,3.58,4.611672,-0.07,1.1,-0.03,43.1
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,577828.56830,2.44,2.041472,-0.04,1.2,-0.58,49.0
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,515395.95730,2.33,7.226063,-0.65,1.3,-0.64,44.8
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,38665.63686,4.19,3.066667,1.29,0.7,1.78,77.2
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,32545.48675,2.64,NaN,NaN,NaN,NaN,NaN

In [143]:
# Afficher toutes les lignes df
with pd.option_context('display.max_rows', None):
    display(df)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Code zone (M49),Quantité_production_poulet_tonne,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance,Cost of animal source foods valeur \n(PPP dollar per person per day),Corruption_Value,mediane_epi
0,710,ZAF,Afrique du Sud,34.6,59392255.0,14.778678,710,1910000.0,-0.75,7.598708e+04,3.58,4.611672,-0.07,1.1,-0.03,43.10
1,8,ALB,Albanie,25.1,2811666.0,103.520000,8,13250.0,0.20,5.778286e+05,2.44,2.041472,-0.04,1.2,-0.58,49.00
2,12,DZA,Algérie,8.6,44177969.0,135.064058,12,273520.2,-0.99,5.153960e+05,2.33,7.226063,-0.65,1.3,-0.64,44.80
3,276,DEU,Allemagne,32.4,83196078.0,NaN,276,1080000.0,0.73,3.866564e+04,4.19,3.066667,1.29,0.7,1.78,77.20
4,20,AND,Andorre,NaN,79034.0,0.845377,NaN,NaN,NaN,3.254549e+04,2.64,NaN,NaN,NaN,NaN,NaN
5,24,AGO,Angola,9.0,34503774.0,631.441955,24,55384.7,-0.71,4.284250e+04,2.21,25.754295,-1.13,1.1,-0.65,30.50
6,660,AIA,Anguilla,NaN,NaN,NaN,NaN,NaN,1.53,NaN,NaN,NaN,0.92,NaN,0.64,NaN
7,10,ATA,Antarctique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28,ATG,Antigua-et-Barbuda,38.7,93219.0,2.700000,28,33.6,0.95,4.354595e+04,2.66,2.062996,-0.19,0.7,0.23,52.40
9,682,SAU,Arabie saoudite,25.3,35950396.0,3.750000,682,930000.0,-0.59,9.044801e+04,3.07,3.063290,0.47,1.0,0.28,44.00
10,32,ARG,Argentine,53.7,45808747.0,94.990742,32,2294101.4,0.00,1.509614e+04,2.89,NaN,-0.39,NaN,-0.42,52.20
11,51,ARM,Arménie,28.0,2790974.0,503.769675,51,14600.0,-0.80,2.021108e+06,2.45,7.184836,-0.28,1.0,0.05,52.30
12,533,ABW,Aruba,NaN,106537.0,1.790000,NaN,NaN,1.43,4.736943e+04,2.64,NaN,1.08,0.8,0.80,NaN
13,36,AUS,Australie,48.2,25685412.0,1.331224,36,1292240.0,0.84,8.711930e+04,3.79,2.863910,1.47,0.5,1.71,74.12
14,40,AUT,Autriche,33.4,8955797.0,NaN,40,129390.0,0.90,4.054430e+04,3.96,2.766667,1.53,0.6,1.24,78.97
15,31,AZE,Azerbaïdjan,18.2,10137750.0,1.700000,31,124388.0,-0.84,3.030787e+03,2.40,6.650299,0.21,1.0,-0.85,46.50
16,44,BHS,Bahamas,48.9,407906.0,1.000000,44,6138.0,0.85,2.766500e+04,2.62,2.904913,0.42,NaN,1.15,54.99
17,48,BHR,Bahreïn,39.0,1463265.0,0.376000,48,8262.0,-0.52,8.685221e+03,3.09,-0.606319,0.68,1.2,0.14,51.00
18,50,BGD,Bangladesh,2.2,169356251.0,85.083763,50,215838.4,-1.04,1.673363e+05,2.56,5.545654,-0.66,1.4,-0.99,29.00
19,52,BRB,Barbade,37.5,281200.0,2.000000,52,13183.0,1.12,2.862436e+04,2.64,NaN,0.50,NaN,1.21,53.20
20,56,BEL,Belgique,31.3,11586195.0,NaN,56,447710.0,0.66,3.900237e+04,4.08,2.440249,1.09,0.5,1.46,73.30
21,84,BLZ,Belize,23.9,400031.0,2.000000,84,19187.0,0.27,1.153223e+04,2.64,3.235637,-0.53,0.7,-0.33,50.00
22,60,BMU,Bermudes,NaN,63764.0,1.000000,NaN,NaN,1.00,9.934455e+04,2.64,NaN,1.47,0.6,1.28,NaN
23,64,BTN,Bhoutan,6.3,777486.0,73.918013,64,1865.5,0.80,2.227338e+05,2.37,7.346814,0.70,1.3,1.51,42.50
24,104,MMR,Birmanie,8.9,53798084.0,NaN,104,620000.0,-2.08,1.376324e+06,2.28,NaN,-1.41,NaN,-1.05,25.10
25,112,BLR,Biélorussie,41.3,9302585.0,2.538675,112,503200.0,-0.75,1.357257e+04,2.48,9.460284,-0.80,0.9,-0.26,53.00
26,68,BOL,Bolivie,35.1,12079472.0,6.910000,68,506148.1,-0.28,3.948861e+03,2.33,0.737384,-0.76,1.2,-0.88,44.30
27,70,BIH,Bosnie-Herzégovine,20.7,3270943.0,1.653606,70,63703.0,-0.42,1.048877e+04,2.65,NaN,-1.07,1.0,-0.67,41.84
28,72,BWA,Botswana,15.9,2588423.0,11.087258,72,1266.8,1.04,7.252043e+04,2.70,7.240978,0.32,1.2,0.67,51.70
29,96,BRN,Brunei,NaN,445373.0,1.343807,96,31444.6,1.17,4.267829e+04,2.64,1.733414,1.41,1.2,1.22,54.80
30,76,BRA,Brésil,44.4,214326223.0,5.394401,76,14329000.0,-0.42,1.962865e+04,3.13,8.301660,-0.49,0.8,-0.50,51.20
31,100,BGR,Bulgarie,27.5,6877743.0,1.653775,100,90680.0,0.36,1.522833e+04,3.01,3.297744,-0.17,1.0,-0.26,57.00
32,854,BFA,Burkina Faso,15.1,22100683.0,554.530675,854,149121.0,-1.64,4.386156e+05,2.42,3.653533,-0.76,0.9,-0.08,38.30
33,108,BDI,Burundi,1.7,12551213.0,1975.950881,108,8228.5,-1.26,1.466705e+05,2.37,8.404538,-1.36,1.6,-1.60,27.43
34,204,BEN,Bénin,7.5,12996895.0,554.607799,204,9359.4,-0.40,7.177769e+05,2.63,1.733540,-0.24,1.2,-0.17,30.00
35,116,KHM,Cambodge,5.8,16589023.0,4098.722795,116,16296.8,-0.13,3.405004e+06,2.48,2.920735,-0.48,1.1,-1.20,33.60
36,120,CMR,Cameroun,6.9,27198628.0,554.530675,120,104762.1,-1.39,8.501724e+05,2.39,2.271858,-0.90,1.4,-1.12,33.60
37,124,CAN,Canada,37.2,38239864.0,1.253877,124,1334020.0,0.96,5.672647e+04,3.95,3.395193,1.56,0.9,1.62,71.00
38,132,CPV,Cap-Vert,17.6,587925.0,93.218092,132,581.4,0.89,3.032035e+05,2.64,1.862153,0.00,0.9,1.02,41.90
39,152,CHL,Chili,41.7,19493184.0,758.955379,152,680289.5,0.16,1.021917e+07,3.08,4.524568,0.59,0.8,0.96,55.30
40,196,CYP,Chypre,30.3,1244188.0,NaN,196,26640.0,0.42,2.651536e+04,2.94,2.446089,0.70,0.8,0.37,64.80
41,170,COL,Colombie,27.4,51516562.0,3744.244167,170,1694334.9,-0.95,1.759129e+07,2.77,3.495058,-0.05,0.9,-0.37,52.90
42,174,COM,Comores,16.1,821625.0,415.955849,174,585.0,-0.23,5.175177e+05,2.43,NaN,-1.81,1.4,-1.31,42.50
43,408,PRK,Corée du Nord,6.0,25971909.0,NaN,408,30902.2,-0.48,NaN,2.64,NaN,-1.58,NaN,-1.62,NaN
44,410,KOR,Corée du Sud,34.6,51769539.0,1143.951667,410,935000.0,0.63,3.706253e+07,3.67,2.498333,1.37,1.4,0.73,62.30
45,188,CRI,Costa Rica,26.7,5153957.0,620.784720,188,147816.0,0.86,7.235903e+06,2.68,1.726478,0.22,1.0,0.47,52.50
46,191,HRV,Croatie,36.9,3878981.0,6.360083,191,58610.0,0.62,1.398900e+04,3.00,2.554507,0.55,1.0,0.04,63.10
47,192,CUB,Cuba,23.2,11256372.0,NaN,192,17918.0,0.39,4.560421e+03,2.19,NaN,-0.25,NaN,-0.03,48.40
48,531,CUW,Curaçao,NaN,152369.0,1.790000,NaN,NaN,NaN,2.689107e+04,2.64,NaN,NaN,0.7,NaN,NaN
49,384,CIV,Côte d'Ivoire,8.5,27478249.0,554.530675,384,63949.0,-0.72,1.368845e+06,2.71,4.091952,-0.54,1.4,-0.40,32.80
50,208,DNK,Danemark,28.9,5856733.0,6.287113,208,163100.0,0.93,3.983301e+05,3.95,1.853045,1.96,0.6,2.33,81.60
51,262,DJI,Djibouti,7.4,1105557.0,177.721000,NaN,NaN,-0.57,5.001280e+05,2.18,1.181918,-0.83,1.3,-0.80,40.04
52,212,DMA,Dominique,36.8,72412.0,2.700000,212,369.4,1.33,1.534939e+04,2.64,1.483194,-0.12,0.9,0.55,51.20
53,724,ESP,Espagne,42.1,47415794.0,NaN,724,1331410.0,0.51,2.378665e+04,3.73,3.093135,0.91,0.7,0.72,74.30
54,233,EST,Estonie,27.9,1330932.0,NaN,233,23300.0,0.75,1.940012e+04,3.18,4.653167,1.35,0.8,1.51,64.31
55,748,SWZ,Eswatini,12.7,1192271.0,14.783435,748,5520.6,-0.35,3.916264e+04,2.64,NaN,-0.75,1.3,-0.70,40.32
56,242,FJI,Fidji,20.8,924610.0,2.070633,242,25715.0,0.72,9.107318e+03,2.27,0.155856,0.65,1.1,0.44,34.40
57,246,FIN,Finlande,32.5,5541017.0,NaN,246,138600.0,0.96,4.160897e+04,3.94,2.194574,1.92,0.6,2.24,78.64
58,250,FRA,France,38.3,67764304.0,NaN,250,1143000.0,0.33,3.425124e+04,3.81,1.642331,1.23,0.6,1.28,80.00
59,266,GAB,Gabon,33.5,2341179.0,554.530675,266,4111.4,-0.08,2.445214e+06,2.16,1.086907,-0.82,1.0,-0.87,45.80
60,270,GMB,Gambie,7.4,2639916.0,51.484444,270,1098.6,0.04,2.477356e+04,2.47,7.370348,-0.68,0.9,-0.38,36.40
61,288,GHA,Ghana,11.2,32833031.0,5.805700,288,65190.0,0.07,5.317575e+03,2.40,9.971089,-0.18,1.6,-0.13,27.70
62,292,GIB,Gibraltar,NaN,32669.0,0.727065,NaN,NaN,NaN,NaN,2.64,NaN,NaN,NaN,NaN,NaN
63,308,GRD,Grenade,35.7,124610.0,2.700000,308,421.2,1.04,1.803916e+04,2.56,1.219512,0.02,1.0,0.49,47.90
64,304,GRL,Groenland,NaN,56653.0,NaN,NaN,NaN,1.88,2.778423e+05,2.64,NaN,0.75,NaN,1.00,NaN
65,300,GRC,Grèce,31.6,10569207.0,NaN,300,235500.0,0.10,1.708938e+04,3.11,1.223825,0.41,0.9,0.18,69.10
66,312,GLP,Guadeloupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,316,GUM,Guam,NaN,170534.0,NaN,NaN,NaN,0.88,3.024030e+04,2.64,NaN,0.64,NaN,1.28,NaN
68,320,GTM,Guatemala,18.9,17109746.0,7.734388,320,342169.0,-0.40,3.194772e+04,2.56,4.261051,-0.78,0.9,-1.19,31.80
69,831,GGY,Guernesey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,324,GIN,Guinée,8.2,13531906.0,NaN,324,14996.9,-0.94,5.434176e+06,2.51,12.597288,-0.95,1.1,-1.02,31.60
71,226,GNQ,Guinée équatoriale,NaN,1634466.0,554.530675,226,260.3,-0.20,2.988914e+06,2.39,-0.097101,-1.18,1.1,-1.59,44.80
72,624,GNB,Guinée-Bissau,6.7,2060721.0,554.530675,624,3076.9,-0.28,4.272210e+05,2.28,2.242489,-1.45,1.1,-1.32,40.20
73,328,GUY,Guyana,32.4,804567.0,208.500000,328,48945.0,-0.14,2.234476e+06,2.33,5.032856,-0.26,NaN,-0.19,38.50
74,254,GUF,Guyane,NaN,NaN,NaN,NaN,NaN,0.33,NaN,NaN,NaN,1.22,NaN,0.90,NaN
75,268,GEO,Géorgie,17.3,3708610.0,3.221558,268,25000.0,-0.43,1.390224e+04,2.46,9.566914,0.62,NaN,0.66,41.30
76,239,SGS,Géorgie du Sud-et-les îles Sandwich du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,332,HTI,Haïti,10.5,11447569.0,89.226637,332,8753.3,-1.13,5.366283e+04,2.05,16.841524,-2.22,NaN,-1.44,27.00
78,340,HND,Honduras,17.4,10278345.0,24.016655,340,243580.7,-0.63,2.198621e+04,2.54,4.480880,-0.82,1.1,-1.09,37.80
79,344,HKG,Hong Kong,72.7,7413100.0,7.773250,344,25550.9,0.26,3.868790e+05,3.95,1.568758,1.49,1.2,1.68,NaN
80,348,HUN,Hongrie,32.7,9709891.0,303.140833,348,367610.0,0.80,4.335626e+06,3.16,5.110965,0.60,0.8,0.01,63.70
81,368,IRQ,Irak,8.5,43533592.0,1450.000000,368,144702.0,-2.38,4.555973e+06,2.15,6.041865,-1.32,1.4,-1.27,39.50
82,372,IRL,Irlande,40.7,5033164.0,NaN,372,147770.0,0.84,8.164772e+04,3.75,2.340341,1.47,0.5,1.62,72.80
83,352,ISL,Islande,42.6,372520.0,126.988860,352,8997.0,1.37,7.183250e+06,3.28,4.444240,1.60,0.7,1.76,72.30
84,376,ISR,Israël,49.1,9371400.0,3.230198,376,541292.0,-1.12,1.584777e+05,3.36,1.510200,1.25,0.7,0.83,65.80
85,380,ITA,Italie,31.3,59133173.0,NaN,380,1068500.0,0.55,2.882404e+04,3.70,1.873783,0.33,0.8,0.52,71.00
86,388,JAM,Jamaïque,29.5,2827695.0,150.790106,388,125192.0,0.22,2.999135e+05,2.38,5.862782,0.38,1.0,-0.05,48.20
87,392,JPN,Japon,25.4,125681593.0,109.754324,392,2342999.8,1.02,4.321448e+06,4.03,-0.233353,1.36,1.0,1.54,74.69
88,832,JEY,Jersey,NaN,NaN,NaN,NaN,NaN,1.28,NaN,NaN,NaN,1.15,NaN,1.00,NaN
89,400,JOR,Jordanie,16.6,11148278.0,0.710000,400,246582.0,-0.32,2.767749e+03,2.69,1.346094,0.20,0.9,0.03,53.40
90,398,KAZ,Kazakhstan,33.9,19191356.0,425.907500,398,263560.5,-0.23,7.834362e+05,2.57,8.041471,0.03,0.7,-0.26,44.70
91,404,KEN,Kenya,5.1,53005614.0,109.637747,404,89450.0,-1.03,1.772631e+05,2.64,6.107936,-0.32,1.2,-0.74,34.70
92,417,KGZ,Kirghizistan,19.5,6773400.0,84.640822,417,11069.0,-0.47,9.459085e+04,2.23,11.905040,-0.78,0.9,-1.15,39.80
93,296,KIR,Kiribati,23.5,128874.0,1.331224,296,991.0,1.14,2.614957e+03,2.64,2.053617,0.09,NaN,0.28,49.00
94,414,KWT,Koweït,38.1,4250114.0,0.301643,414,64345.3,0.26,9.128203e+03,2.89,3.423629,-0.07,0.5,-0.06,53.60
95,638,REU,La Réunion,NaN,NaN,NaN,NaN,NaN,0.23,NaN,NaN,NaN,0.92,NaN,0.64,NaN
96,418,LAO,Laos,13.9,7425057.0,9697.915789,418,36417.4,0.71,1.810329e+07,2.34,3.755620,-0.62,1.2,-1.05,34.80
97,426,LSO,Lesotho,10.9,2281454.0,14.778678,426,1060.1,-0.21,8.747909e+03,2.34,6.047746,-0.95,1.3,-0.35,32.30
98,428,LVA,Lettonie,31.2,1884490.0,NaN,428,35080.0,0.67,1.485474e+04,3.06,3.275829,0.83,0.9,0.72,61.60
99,422,LBN,Liban,16.3,5592631.0,1507.500000,422,126642.4,-1.48,7.839920e+06,2.73,154.756096,-1.31,1.8,-1.25,45.40
100,430,LBR,Liberia,11.2,5193416.0,166.153701,430,14336.7,-0.29,6.737377e+02,2.30,NaN,-1.41,1.0,-0.94,24.90
101,434,LBY,Libye,25.2,6735277.0,4.514425,434,131084.7,-2.31,1.519171e+04,2.25,2.868330,-1.75,NaN,-1.58,49.79
102,438,LIE,Liechtenstein,NaN,39039.0,NaN,NaN,NaN,1.60,NaN,2.64,NaN,1.47,NaN,1.67,NaN
103,440,LTU,Lituanie,40.1,2800839.0,NaN,440,85030.0,0.81,1.648699e+04,3.07,4.683544,1.02,0.8,0.82,62.90
104,442,LUX,Luxembourg,36.7,640064.0,NaN,442,0.0,1.19,9.952646e+04,3.74,2.526920,1.68,0.5,1.84,79.12
105,446,MAC,Macao,47.8,686607.0,8.005532,446,3216.7,1.03,3.610887e+05,2.64,0.026454,1.08,NaN,0.82,NaN
106,807,MKD,Macédoine du Nord,19.3,1837114.0,52.102158,807,1695.0,0.06,2.550517e+05,2.65,3.230749,-0.12,1.2,-0.37,55.40
107,450,MDG,Madagascar,2.5,28915653.0,3829.977849,450,52991.4,-0.54,7.430365e+05,2.28,5.812251,-1.03,1.3,-0.95,28.00
108,458,MYS,Malaisie,28.7,33573874.0,4.143298,458,1583219.5,0.06,4.142041e+04,3.43,2.477102,0.95,0.8,0.15,47.90
109,454,MWI,Malawi,12.0,19889742.0,NaN,454,143705.3,-0.11,3.743852e+05,2.71,9.330144,-0.79,1.2,-0.32,40.60
110,462,MDV,Maldives,12.5,521457.0,15.372698,NaN,NaN,0.53,1.560317e+05,2.54,0.543150,0.32,0.9,-0.38,37.40
111,466,MLI,Mali,3.8,21904983.0,554.530675,466,59780.0,-2.33,2.518850e+05,2.37,3.925603,-1.25,1.3,-0.89,29.40
112,238,FLK,Malouines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,470,MLT,Malte,28.1,518536.0,NaN,470,4070.0,0.89,2.627504e+04,2.92,1.497892,0.85,0.9,0.29,75.20
114,504,MAR,Maroc,15.6,37076584.0,8.988484,504,525000.0,-0.40,3.117180e+04,2.60,1.401959,-0.17,0.8,-0.42,42.30
115,474,MTQ,Martinique,NaN,NaN,NaN,NaN,NaN,0.63,NaN,NaN,NaN,0.92,NaN,0.64,NaN
116,480,MUS,Maurice,24.8,1266334.0,41.692133,480,49100.0,0.83,3.590104e+05,2.47,4.028529,0.81,1.0,0.44,45.10
117,478,MRT,Mauritanie,16.2,4614974.0,36.063333,478,3992.5,-0.56,5.319261e+04,2.29,3.565165,-0.78,1.1,-0.84,28.10
118,175,MYT,Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,484,MEX,Mexique,34.9,126705138.0,20.272408,484,3668551.3,-0.69,1.838971e+05,3.02,5.689208,-0.34,0.9,-1.02,52.60
120,498,MDA,Moldavie,26.5,2595809.0,17.680466,498,51599.9,-0.21,6.940568e+04,2.36,5.106411,-0.44,0.8,-0.47,44.40
121,492,MCO,Monaco,NaN,36686.0,NaN,NaN,NaN,1.17,1.823393e+05,2.64,NaN,2.03,NaN,1.28,NaN
122,496,MNG,Mongolie,64.7,3347782.0,2849.288615,496,245.8,0.71,8.092422e+06,2.15,7.352812,-0.52,0.8,-0.55,32.20
123,500,MSR,Montserrat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,499,MNE,Monténégro,36.6,619211.0,0.845377,499,1332.7,-0.05,6.232659e+03,2.49,2.410802,-0.03,0.9,-0.04,46.90
125,508,MOZ,Mozambique,4.6,32077072.0,65.465000,508,135708.0,-1.26,3.059042e+04,2.46,6.408477,-0.75,1.2,-0.82,33.90
126,516,NAM,Namibie,18.4,2530151.0,14.778675,516,11663.2,0.52,5.451653e+04,2.48,3.616905,0.03,1.0,0.24,50.90
127,520,NRU,Nauru,54.8,12511.0,1.331224,520,4.0,0.79,1.012020e+04,2.64,NaN,0.10,NaN,0.60,NaN
128,558,NIC,Nicaragua,14.4,6850540.0,35.171017,558,143283.0,-0.47,2.763257e+04,2.56,4.928414,-0.88,1.2,-1.25,39.20
129,562,NER,Niger,4.1,25252722.0,554.530675,562,20206.7,-1.54,3.001643e+05,2.37,3.837868,-0.64,1.5,-0.58,35.74
130,566,NGA,Nigeria,3.3,213401323.0,401.152029,566,342959.3,-1.79,3.438721e+05,2.50,16.952846,-1.03,1.0,-1.10,31.00
131,570,NIU,Niue,NaN,NaN,NaN,570,24.8,1.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,578,NOR,Norvège,31.2,5408320.0,8.590000,578,106043.0,1.09,6.274947e+05,3.80,3.483881,1.80,0.9,2.11,77.49
133,540,NCL,Nouvelle-Calédonie,39.0,270390.0,100.880223,540,888.0,NaN,3.511520e+06,2.64,NaN,NaN,NaN,NaN,NaN
134,554,NZL,Nouvelle-Zélande,37.9,5111300.0,1.413800,554,224397.0,1.40,5.911676e+04,3.59,3.941121,1.31,0.7,2.17,71.30
135,524,NPL,Népal,9.3,30034989.0,118.134082,524,226959.0,-0.19,7.973426e+04,2.31,4.149680,-0.93,0.9,-0.56,31.44
136,512,OMN,Oman,22.5,4520471.0,0.384500,512,6563.9,0.43,7.665247e+03,2.87,1.682212,-0.16,0.8,0.06,38.50
137,800,UGA,Ouganda,4.8,45853778.0,3587.051707,800,69340.3,-0.94,2.854313e+06,2.68,2.204572,-0.60,1.2,-1.03,35.80
138,860,UZB,Ouzbékistan,19.7,34915100.0,10609.464390,860,123600.0,-0.25,4.351648e+06,2.43,10.849240,-0.27,1.4,-0.83,44.30
139,586,PAK,Pakistan,9.5,231402117.0,162.906254,586,1809000.0,-1.71,1.689769e+05,2.68,9.496211,-0.44,1.1,-0.81,33.10
140,585,PLW,Palaos,NaN,18024.0,1.000000,NaN,NaN,1.17,1.225911e+04,2.64,2.612482,0.37,NaN,0.60,NaN
141,275,PSE,Palestine,NaN,4922749.0,NaN,275,37625.5,NaN,3.051486e+03,2.64,1.237481,NaN,0.7,NaN,NaN
142,591,PAN,Panama,39.3,4351267.0,1.000000,591,197594.0,0.31,1.523335e+04,2.97,1.630703,0.12,1.2,-0.59,50.50
143,598,PNG,Papouasie-Nouvelle-Guinée,29.0,9949437.0,3.508772,598,6708.4,-0.58,6.345721e+03,2.30,4.483590,-0.89,NaN,-0.77,32.40
144,600,PRY,Paraguay,17.3,6703799.0,6774.162735,600,75054.5,0.00,3.206706e+07,2.64,4.787983,-0.66,0.8,-1.03,46.40
145,528,NLD,Pays-Bas,31.2,17533044.0,NaN,528,869380.0,0.89,4.408558e+04,4.15,2.675720,1.73,0.6,2.00,75.30
146,535,BES,Pays-Bas caribéens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,608,PHL,Philippines,15.9,113880328.0,49.254598,608,1343496.3,-0.98,1.628032e+05,2.92,3.927180,0.04,0.8,-0.53,38.40
148,616,POL,Pologne,41.4,37747124.0,3.861917,616,2096770.0,0.49,5.979645e+04,3.38,5.055027,0.25,0.8,0.55,60.90
149,258,PYF,Polynésie française,41.8,304032.0,100.880223,258,591.3,NaN,1.805823e+06,2.64,NaN,NaN,NaN,NaN,NaN
150,630,PRI,Porto Rico,NaN,3262693.0,NaN,630,24479.0,0.49,2.965559e+04,2.64,NaN,-0.30,NaN,0.37,NaN
151,620,PRT,Portugal,40.9,10361831.0,NaN,620,300040.0,0.94,1.875375e+04,3.45,1.265657,0.95,0.7,0.74,67.00
152,604,PER,Pérou,25.3,33715471.0,3.880554,604,1751607.8,-0.36,1.636821e+04,2.72,4.271664,-0.29,1.0,-0.65,44.00
153,634,QAT,Qatar,37.4,2688235.0,3.640000,634,35344.0,0.83,2.449823e+05,3.32,2.304466,1.08,0.7,0.78,37.10
154,642,ROU,Roumanie,28.8,19122059.0,4.160417,642,451850.0,NaN,2.469172e+04,2.97,5.052329,NaN,1.0,NaN,64.70
155,826,GBR,Royaume-Uni,36.2,67026292.0,0.727065,826,1841000.0,0.49,3.003684e+04,3.96,2.518371,1.24,0.5,1.64,79.89
156,643,RUS,Russie,34.8,144746762.0,73.654350,643,4617338.0,-0.71,6.396779e+05,2.64,6.694459,-0.21,0.6,-0.92,50.50
157,646,RWA,Rwanda,3.7,13461888.0,988.624807,646,13457.7,0.07,7.271479e+05,2.42,-0.391347,0.23,1.4,0.57,33.80
158,732,ESH,République arabe sahraouie démocratique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,140,CAF,République centrafricaine,17.6,5457154.0,554.530675,140,6444.4,-2.13,1.425765e+05,2.50,4.259364,-1.67,1.3,-1.25,36.90
160,214,DOM,République dominicaine,24.4,11117873.0,57.221117,214,347491.6,0.29,2.474187e+05,2.58,8.243003,0.00,1.2,-0.59,46.30
161,178,COG,République du Congo,22.6,5835806.0,554.530675,178,6883.8,-0.23,7.616007e+05,2.38,1.715643,-1.32,1.1,-1.39,40.10
162,180,COD,République démocratique du Congo,2.3,95894118.0,1989.391471,180,10532.0,NaN,1.426460e+05,2.38,NaN,NaN,1.7,NaN,36.40
163,652,BLM,Saint-Barthélemy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,659,KNA,Saint-Christophe-et-Niévès,43.3,47606.0,2.700000,659,16.5,0.95,4.241734e+04,2.64,1.195689,0.36,0.7,0.41,NaN
165,674,SMR,Saint-Marin,NaN,33745.0,0.845377,NaN,NaN,1.17,3.689799e+04,2.64,NaN,1.75,NaN,1.28,NaN
166,534,SXM,Saint-Martin,NaN,40708.0,1.790000,NaN,NaN,NaN,5.569649e+04,2.64,NaN,NaN,NaN,NaN,NaN
167,663,MAF,Saint-Martin,NaN,31948.0,NaN,NaN,NaN,NaN,1.598449e+04,2.64,NaN,NaN,NaN,NaN,NaN
168,666,SPM,Saint-Pierre-et-Miquelon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,336,VAT,Saint-Siège (État de la Cité du Vatican),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,670,VCT,Saint-Vincent-et-les-Grenadines,48.9,104332.0,2.700000,670,452.7,1.04,2.234271e+04,2.64,1.572729,0.30,0.8,0.77,53.20
171,654,SHN,"Sainte-Hélène, Ascension et Tristan da Cunha",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,662,LCA,Sainte-Lucie,48.1,179651.0,2.700000,662,1366.3,0.83,2.607255e+04,2.64,2.410703,-0.12,0.9,0.56,49.40
173,222,SLV,Salvador,19.2,6314167.0,1.000000,222,155405.5,-0.09,4.153954e+03,2.70,3.466926,-0.34,NaN,-0.55,43.10
174,882,WSM,Samoa,47.4,218764.0,2.556092,882,403.3,1.11,9.015912e+03,2.64,3.133205,0.38,NaN,0.59,37.30
175,16,ASM,Samoa américaines,NaN,45035.0,NaN,NaN,NaN,1.07,1.407794e+04,2.64,NaN,0.64,NaN,1.28,NaN
176,678,STP,Sao Tomé-et-Principe,12.3,223107.0,20.710402,678,701.2,0.59,1.860629e+04,2.62,8.137770,-0.76,0.9,0.23,52.90
177,688,SRB,Serbie,33.1,6834326.0,99.395942,688,110528.0,-0.09,7.753052e+05,2.69,4.085103,0.01,1.0,-0.46,55.20
178,690,SYC,Seychelles,32.2,99258.0,16.920523,690,1470.2,0.74,2.286981e+05,2.64,9.769099,0.90,1.0,1.60,58.20
179,694,SLE,Sierra Leone,5.6,8420641.0,10.439425,694,19748.0,-0.10,1.237262e+03,2.11,11.873959,-1.15,1.2,-0.46,32.70
180,702,SGP,Singapour,NaN,5453566.0,1.343483,702,75962.0,1.44,9.299130e+04,4.14,2.304860,2.25,0.7,2.14,58.10
181,703,SVK,Slovaquie,25.7,5447247.0,NaN,NaN,NaN,0.62,1.667251e+04,3.15,3.149606,0.49,0.6,0.21,68.30
182,705,SVN,Slovénie,27.5,2108079.0,NaN,705,66600.0,0.76,2.234025e+04,3.19,1.917065,1.14,0.7,0.69,67.57
183,706,SOM,Somalie,NaN,17065581.0,NaN,706,3986.1,-2.73,1.599362e+07,1.99,NaN,-2.08,1.3,-1.80,NaN
184,728,SSD,Soudan du Sud,9.9,10748272.0,306.354620,728,49274.8,-2.29,NaN,2.64,10.516716,-2.40,1.5,-1.84,NaN

# **Calcul des % NAN**

Suppression des colonnes ayant plus de 30% de valeurs manquantes :
* Taux_de_fret_unitaire_EUkg_Value 65% NaN
* Prix_production_poulet_US$_tonne 84% NaN

In [144]:
# Calcul du % des NaN
nan_percentage = df.isna().mean() * 100
print(nan_percentage)

num_pays                                                                 0.000000
code_pays                                                                0.000000
pays                                                                     0.000000
Dispo_proteine_g_personne_jour                                          26.446281
person_2021                                                             14.049587
Taux_change_unit_devises_local_par_$US_Moy_period                       31.404959
Code zone (M49)                                                         22.727273
Quantité_production_poulet_tonne                                       22.727273
Stabilité_Politique                                                     17.355372
PIB_par_habitant                                                        18.181818
lpi_AVG_2007_2022                                                       14.049587
Inflation_prix_à_la consommation_%_annuel                               32.231405
Governance_Performance                                                  18.181818
Cost of animal source foods valeur \n(PPP dollar per person per day)    33.471074
Corruption_Value                                                        18.181818
mediane_epi                                                             28.099174
dtype: float64

# **Imputation par la médiane**

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 16 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   num_pays                                                             242 non-null    object
 1   code_pays                                                            242 non-null    object
 2   pays                                                                 242 non-null    object
 3   Dispo_proteine_g_personne_jour                                       178 non-null    float64
 4   person_2021                                                          208 non-null    float64
 5   Taux_change_unit_devises_local_par_$US_Moy_period                    166 non-null    float64
 6   Code zone (M49)                                                      187 non-null    object
 7   Quantité_production_poulet_tonne                                    187 non-null    float64
 8   Stabilité_Politique                                                  200 non-null    float64
 9   PIB_par_habitant                                                     198 non-null    float64
 10  lpi_AVG_2007_2022                                                    208 non-null    float64
 11  Inflation_prix_à_la consommation_%_annuel                            164 non-null    float64
 12  Governance_Performance                                               198 non-null    float64
 13  Cost of animal source foods valeur
(PPP dollar per person per day)  161 non-null    float64
 14  Corruption_Value                                                     198 non-null    float64
 15  mediane_epi                                                          174 non-null    float64
dtypes: float64(12), object(4)
memory usage: 30.4+ KB

In [146]:
# Remplacer Nan par médiane
for column in df.select_dtypes(include=np.number).columns:
    df[column] = df[column].fillna(df[column].median())

In [147]:
# diviser Quantité_production_poulet_tonne par le nombre de population
df['Quantité_production_poulet_kg_par_pers'] = (df['Quantité_production_poulet_tonne'] * 1000) / df['person_2021']


#========== Supprimer les colonnes Quantité_production_poulet_tonne, Code Zone M49
df = df.drop(columns=['Quantité_production_poulet_tonne', 'Code zone (M49)'])
df.round(2)
df.head(5)

,num_pays,code_pays,pays,Dispo_proteine_g_personne_jour,person_2021,Taux_change_unit_devises_local_par_$US_Moy_period,Stabilité_Politique,PIB_par_habitant,lpi_AVG_2007_2022,Inflation_prix_à_la consommation_%_annuel,Governance_Performance,Cost of animal source foods valeur \n(PPP dollar per person per day),Corruption_Value,mediane_epi,Quantité_production_poulet_kg_par_pers
0,710,ZAF,Afrique du Sud,34.60,59392255.0,14.778678,-0.75,75987.07811,3.58,4.611672,-0.070,1.1,-0.030,43.1,32.159075
1,8,ALB,Albanie,25.10,2811666.0,103.520000,0.20,577828.56830,2.44,2.041472,-0.040,1.2,-0.580,49.0,4.712509
2,12,DZA,Algérie,8.60,44177969.0,135.064058,-0.99,515395.95730,2.33,7.226063,-0.650,1.3,-0.640,44.8,6.191326
3,276,DEU,Allemagne,32.40,83196078.0,17.300494,0.73,38665.63686,4.19,3.066667,1.290,0.7,1.780,77.2,12.981381
4,20,AND,Andorre,25.15,79034.0,0.845377,0.18,32545.48675,2.64,3.475403,-0.045,1.0,-0.055,45.6,756.383329

# **Télechargement des données nettoyées : df en csv**

In [153]:
import os

# Le chemin vers Mon drive
#chemin_fichier = "/content/drive/MyDrive/MON_dossier/df.csv"

# Créer les répertoires manquants si nécessaire
os.makedirs(os.path.dirname(chemin_fichier), exist_ok=True)

# Enregistrez le dataframe en CSV
df_csv = df.to_csv(chemin_fichier, index=False)

print(f"Fichier enregistré avec succès à l'emplacement : {chemin_fichier}")

Fichier enregistré avec succès à l'emplacement : /content/drive/MyDrive/1. Alternance Data Analyst /09.PROJET 9/DONNEES 9/Données P9/df.csv